export type Category = {
  id: string;
  slug: string;
  name_kn: string;
  name_en: string;
};
export type Post = {
  id: string;
  slug: string;
  title_kn: string;
  title_en: string;
  summary_en?: string;
  body_en?: string;
  title_translit: string;
  summary_kn: string;
  body_html: string;
  type: "article" | "video" | "short";
  status: "draft" | "published" | "scheduled" | "archived";
  event_date: string;
  published_at: string;
  event_place: string;
  thumbnail_url: string;
  video_url: string | null;
  video_id: string | null;
  video_provider: "youtube" | "facebook" | "none";
  category_slugs: string[];
  is_featured: boolean;
  is_breaking: boolean;
  is_live: boolean;
  duration_seconds: number | null;
  view_count: number;
  is_seed: boolean;
  image_credit?: string;
  embargo_until?: string;
  summary_points?: string[];
  hide_ads?: boolean;
  meaningful_update_at?: string;
  author_id?: string;
  public_author_id?: string;
  place_id?: string;
  event_id?: string;
  scheduled_for?: string;
  primary_category?: string;
  tag_ids?: string[];
  transcript?: string;
  seo_title?: string;
  seo_description?: string;
  sponsor_name?: string;
  breaking_until?: string;
  allow_comments?: boolean;
  early_access_until?: string;
  audio_enabled?: boolean;
  key_points?: { seconds: number; label_kn: string }[];
  media_images?: { url: string; credit: string }[];
  tags?: { slug: string; name_kn: string }[];
};
export type NewsEvent = {
  id: string;
  slug: string;
  name_kn: string;
  name_en: string;
  start_date: string;
  end_date: string;
  place: string;
  district: string;
  place_id?: string;
  organiser: string;
  description_kn: string;
  is_seed: boolean;
};
