-- Translations that live inside jsonb payloads: gallery captions, story slide
-- text, quiz questions and topic timelines.
-- Apply supabase/migrations/20260918210000_v7_attribution.sql first.
-- Each statement replaces the whole column, so unlike the per-language files
-- this one carries Kannada, English and Hindi together. Safe to re-run, but it
-- overwrites any edit made to these payloads in the database.
begin;
update public.galleries set images='[{"url":"/images/hill.webp","caption":"ಪರಂಪರೆಯ ಚಿತ್ರ — ಮಾದರಿ ವಿನ್ಯಾಸ","caption_en":"A Heritage Photograph — Sample Layout","caption_hi":"परंपरा का चित्र — नमूना विन्यास","credit":"Wikimedia Commons — docs/ASSETS.md"},{"url":"/images/temple.webp","caption":"ಪರಂಪರೆಯ ಚಿತ್ರ — ಮಾದರಿ ವಿನ್ಯಾಸ","caption_en":"A Heritage Photograph — Sample Layout","caption_hi":"परंपरा का चित्र — नमूना विन्यास","credit":"Wikimedia Commons — docs/ASSETS.md"},{"url":"/images/detail.webp","caption":"ಪರಂಪರೆಯ ಚಿತ್ರ — ಮಾದರಿ ವಿನ್ಯಾಸ","caption_en":"A Heritage Photograph — Sample Layout","caption_hi":"परंपरा का चित्र — नमूना विन्यास","credit":"Wikimedia Commons — docs/ASSETS.md"}]'::jsonb where id='4f09a5e2-08ef-4ce2-8279-ad30975ccf65';
update public.web_stories set slides='[{"image":"/images/hill.webp","text":"ನಮ್ಮ ಪರಂಪರೆ — ಮಾದರಿ ಚಿತ್ರಕಥೆ 1","text_en":"Our Heritage — Sample Web Story 1","text_hi":"हमारी परंपरा — नमूना चित्रकथा 1","credit":"Wikimedia Commons — docs/ASSETS.md","href":"/topic/jain-heritage"},{"image":"/images/temple.webp","text":"ನಮ್ಮ ಪರಂಪರೆ — ಮಾದರಿ ಚಿತ್ರಕಥೆ 2","text_en":"Our Heritage — Sample Web Story 2","text_hi":"हमारी परंपरा — नमूना चित्रकथा 2","credit":"Wikimedia Commons — docs/ASSETS.md","href":"/topic/jain-heritage"},{"image":"/images/detail.webp","text":"ನಮ್ಮ ಪರಂಪರೆ — ಮಾದರಿ ಚಿತ್ರಕಥೆ 3","text_en":"Our Heritage — Sample Web Story 3","text_hi":"हमारी परंपरा — नमूना चित्रकथा 3","credit":"Wikimedia Commons — docs/ASSETS.md","href":"/topic/jain-heritage"},{"image":"/images/landscape.webp","text":"ನಮ್ಮ ಪರಂಪರೆ — ಮಾದರಿ ಚಿತ್ರಕಥೆ 4","text_en":"Our Heritage — Sample Web Story 4","text_hi":"हमारी परंपरा — नमूना चित्रकथा 4","credit":"Wikimedia Commons — docs/ASSETS.md","href":"/topic/jain-heritage"},{"image":"/images/temple.webp","text":"ನಮ್ಮ ಪರಂಪರೆ — ಮಾದರಿ ಚಿತ್ರಕಥೆ 5","text_en":"Our Heritage — Sample Web Story 5","text_hi":"हमारी परंपरा — नमूना चित्रकथा 5","credit":"Wikimedia Commons — docs/ASSETS.md","href":"/topic/jain-heritage"}]'::jsonb where id='fab960f1-2514-43de-8b1a-19c5f01cb599';
update public.quizzes set questions='[{"question":"ಸುದ್ದಿಯನ್ನು ನಂತರ ಓದಲು ಯಾವ ಆಯ್ಕೆ ಬಳಸಬೇಕು?","question_en":"Which option should you use to read a news item later?","question_hi":"समाचार को बाद में पढ़ने के लिए किस विकल्प का उपयोग करें?","options":["ಉಳಿಸಿ","ಹುಡುಕಿ","ಹಂಚಿಕೊಳ್ಳಿ"],"options_en":["Save","Search","Share"],"options_hi":["सहेजें","खोजें","साझा करें"],"answer":0,"explanation":"ಉಳಿಸಿ ಆಯ್ಕೆ ಲೇಖನವನ್ನು ಮತ್ತೆ ತೆರೆಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.","explanation_en":"The Save option lets you open the article again later.","explanation_hi":"सहेजें विकल्प लेख को बाद में दोबारा खोलने में मदद करता है।"},{"question":"ಕಾರ್ಯಕ್ರಮಕ್ಕೆ ಹೋಗುವ ಮೊದಲು ಏನು ದೃಢಪಡಿಸಬೇಕು?","question_en":"What should you confirm before attending an event?","question_hi":"कार्यक्रम में जाने से पहले किसकी पुष्टि करनी चाहिए?","options":["ಚಿತ್ರದ ಬಣ್ಣ","ದಿನಾಂಕ ಮತ್ತು ಸ್ಥಳ","ಪುಟದ ಗಾತ್ರ"],"options_en":["The colour of the photo","The date and the venue","The size of the page"],"options_hi":["चित्र का रंग","तारीख और स्थान","पृष्ठ का आकार"],"answer":1,"explanation":"ದಿನಾಂಕ ಮತ್ತು ಸ್ಥಳವನ್ನು ಆಯೋಜಕರಿಂದ ದೃಢಪಡಿಸಿಕೊಳ್ಳಿ.","explanation_en":"Confirm the date and the venue with the organisers.","explanation_hi":"तारीख और स्थान आयोजकों से पुष्ट कर लें।"}]'::jsonb where id='2dc86f6a-cae5-4be5-8835-06c7ae735d45';
update public.topics set timeline='[{"date":"2026-09-14","text":"ಪರಂಪರೆ ಪರಿಚಯ — ಮಾದರಿ ವರದಿ","text_en":"An Introduction to Our Heritage — Sample Report","text_hi":"परंपरा का परिचय — नमूना रिपोर्ट"}]'::jsonb where id='72d2dcac-34fe-406a-8d8b-45ed50e2d9c3';
commit;
