import { demoPosts, demoEvents } from "@/lib/data/demo";
import type { DataTables, Place } from "./types";
const id = (kind: string, n: number) => `sample-${kind}-${n}`;
const sample = "ಮಾದರಿ ಮಾಹಿತಿ — ಪ್ರಕಟಣೆಗೆ ಮೊದಲು ಸಂಪಾದಕೀಯ ಪರಿಶೀಲನೆ ಅಗತ್ಯ.";
const sampleEn =
  "Sample information — editorial review required before publication.";
const sampleHi = "नमूना जानकारी — प्रकाशन से पहले संपादकीय समीक्षा आवश्यक।";
const districtNames = [
  ["bagalkote", "ಬಾಗಲಕೋಟೆ", "बागलकोट"],
  ["ballari", "ಬಳ್ಳಾರಿ", "बल्लारी"],
  ["belagavi", "ಬೆಳಗಾವಿ", "बेलगावी"],
  ["bengaluru-urban", "ಬೆಂಗಳೂರು ನಗರ", "बेंगलुरु नगर"],
  ["bengaluru-north", "ಬೆಂಗಳೂರು ಉತ್ತರ", "बेंगलुरु उत्तर"],
  ["bengaluru-south", "ಬೆಂಗಳೂರು ದಕ್ಷಿಣ", "बेंगलुरु दक्षिण"],
  ["bidar", "ಬೀದರ್", "बीदर"],
  ["chamarajanagar", "ಚಾಮರಾಜನಗರ", "चामराजनगर"],
  ["chikkaballapur", "ಚಿಕ್ಕಬಳ್ಳಾಪುರ", "चिक्कबल्लापुर"],
  ["chikkamagaluru", "ಚಿಕ್ಕಮಗಳೂರು", "चिक्कमगलूरु"],
  ["chitradurga", "ಚಿತ್ರದುರ್ಗ", "चित्रदुर्ग"],
  ["dakshina-kannada", "ದಕ್ಷಿಣ ಕನ್ನಡ", "दक्षिण कन्नड़"],
  ["davanagere", "ದಾವಣಗೆರೆ", "दावणगेरे"],
  ["dharwad", "ಧಾರವಾಡ", "धारवाड़"],
  ["gadag", "ಗದಗ", "गदग"],
  ["hassan", "ಹಾಸನ", "हासन"],
  ["haveri", "ಹಾವೇರಿ", "हावेरी"],
  ["kalaburagi", "ಕಲಬುರಗಿ", "कलबुरगी"],
  ["kodagu", "ಕೊಡಗು", "कोडगु"],
  ["kolar", "ಕೋಲಾರ", "कोलार"],
  ["koppal", "ಕೊಪ್ಪಳ", "कोप्पल"],
  ["mandya", "ಮಂಡ್ಯ", "मांड्या"],
  ["mysuru", "ಮೈಸೂರು", "मैसूरु"],
  ["raichur", "ರಾಯಚೂರು", "रायचूर"],
  ["shivamogga", "ಶಿವಮೊಗ್ಗ", "शिवमोग्गा"],
  ["tumakuru", "ತುಮಕೂರು", "तुमकूरु"],
  ["udupi", "ಉಡುಪಿ", "उडुपी"],
  ["uttara-kannada", "ಉತ್ತರ ಕನ್ನಡ", "उत्तर कन्नड़"],
  ["vijayapura", "ವಿಜಯಪುರ", "विजयपुरा"],
  ["vijayanagara", "ವಿಜಯನಗರ", "विजयनगर"],
  ["yadgir", "ಯಾದಗಿರಿ", "यादगिर"],
];
// District slugs are already the standard romanisation, so title-casing them
// gives the English district name rather than leaking a slug into the UI.
const englishDistrict = (slug: string) =>
  slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
// District headquarters and town centres. Every place the weather picker offers
// needs coordinates, because the provider is queried by lat/lng and a place
// without them can only ever render "no weather".
const coordinates: Record<string, [number, number]> = {
  bagalkote: [16.1725, 75.656],
  ballari: [15.1394, 76.9214],
  belagavi: [15.8497, 74.4977],
  "bengaluru-urban": [12.97194, 77.59369],
  "bengaluru-north": [13.1, 77.59],
  "bengaluru-south": [12.71, 77.69],
  bidar: [17.9104, 77.5199],
  chamarajanagar: [11.9261, 76.94],
  chikkaballapur: [13.4355, 77.7315],
  chikkamagaluru: [13.3161, 75.772],
  chitradurga: [14.2251, 76.398],
  "dakshina-kannada": [12.8703, 74.8806],
  davanagere: [14.4644, 75.9218],
  dharwad: [15.4589, 75.0078],
  gadag: [15.429, 75.629],
  hassan: [13.00715, 76.0962],
  haveri: [14.7951, 75.3991],
  kalaburagi: [17.3297, 76.8343],
  kodagu: [12.4244, 75.7382],
  kolar: [13.1367, 78.1292],
  koppal: [15.35, 76.1546],
  mandya: [12.5223, 76.8954],
  mysuru: [12.2958, 76.6394],
  raichur: [16.212, 77.3439],
  shivamogga: [13.9299, 75.5681],
  tumakuru: [13.3392, 77.114],
  udupi: [13.3409, 74.7421],
  "uttara-kannada": [14.8135, 74.1297],
  vijayapura: [16.8302, 75.71],
  vijayanagara: [15.2689, 76.3909],
  yadgir: [16.77, 77.1376],
  shravanabelagola: [12.8556, 76.4886],
  moodbidri: [13.0667, 74.9931],
  karkala: [13.21428, 74.99234],
  dharmastala: [12.94792, 75.38071],
  "bengaluru-city": [12.9716, 77.5946],
  "mysuru-city": [12.2958, 76.6394],
  "hassan-city": [13.00715, 76.0962],
  "tumakuru-city": [13.3392, 77.114],
  "belagavi-city": [15.8497, 74.4977],
};
const places: Place[] = districtNames.map(([slug, name_kn, name_hi], i) => ({
  id: id("place", i + 1),
  slug,
  name_kn,
  name_en: englishDistrict(slug),
  name_hi,
  district: name_kn,
  is_district: true,
  lat: coordinates[slug]?.[0] ?? null,
  lng: coordinates[slug]?.[1] ?? null,
  show_in_weather: slug === "bengaluru-urban" || slug === "hassan",
}));
places.push(
  {
    id: "sample-place-shravana",
    slug: "shravanabelagola",
    name_kn: "ಶ್ರವಣಬೆಳಗೊಳ",
    name_en: "Shravanabelagola",
    name_hi: "श्रवणबेलगोला",
    district: "ಹಾಸನ",
    lat: coordinates.shravanabelagola[0],
    lng: coordinates.shravanabelagola[1],
    show_in_weather: false,
  },
  {
    id: "sample-place-moodbidri",
    slug: "moodbidri",
    name_kn: "ಮೂಡುಬಿದಿರೆ",
    name_en: "Moodbidri",
    name_hi: "मूडबिद्री",
    district: "ದಕ್ಷಿಣ ಕನ್ನಡ",
    lat: coordinates.moodbidri[0],
    lng: coordinates.moodbidri[1],
    show_in_weather: false,
  },
  {
    id: "sample-place-karkala",
    slug: "karkala",
    name_kn: "ಕಾರ್ಕಳ",
    name_en: "Karkala",
    name_hi: "कारकल",
    district: "ಉಡುಪಿ",
    lat: 13.21428,
    lng: 74.99234,
    show_in_weather: true,
  },
  {
    id: "sample-place-dharmastala",
    slug: "dharmastala",
    name_kn: "ಧರ್ಮಸ್ಥಳ",
    name_en: "Dharmastala",
    name_hi: "धर्मस्थल",
    district: "ದಕ್ಷಿಣ ಕನ್ನಡ",
    lat: 12.94792,
    lng: 75.38071,
    show_in_weather: true,
  },
);
places.push(
  ...[
    ["bengaluru-city", "ಬೆಂಗಳೂರು", "Bengaluru", "ಬೆಂಗಳೂರು ನಗರ", "बेंगलुरु"],
    ["mysuru-city", "ಮೈಸೂರು", "Mysuru", "ಮೈಸೂರು", "मैसूरु"],
    ["hassan-city", "ಹಾಸನ", "Hassan", "ಹಾಸನ", "हासन"],
    ["tumakuru-city", "ತುಮಕೂರು", "Tumakuru", "ತುಮಕೂರು", "तुमकूरु"],
    ["belagavi-city", "ಬೆಳಗಾವಿ", "Belagavi", "ಬೆಳಗಾವಿ", "बेलगावी"],
  ].map(([slug, name_kn, name_en, district, name_hi]) => ({
    id: "sample-place-" + slug,
    slug,
    name_kn,
    name_en,
    name_hi,
    district,
    state: "Karnataka",
    is_district: false,
    lat: coordinates[slug]?.[0] ?? null,
    lng: coordinates[slug]?.[1] ?? null,
    show_in_weather: false,
  })),
);
const tags: DataTables["tags"][] = [
  ["ahimsa", "ಅಹಿಂಸೆ", "अहिंसा", "Ahimsa"],
  ["heritage", "ಜೈನ ಪರಂಪರೆ", "जैन परंपरा", "Jain Heritage"],
  ["chaturmasa", "ಚಾತುರ್ಮಾಸ", "चातुर्मास", "Chaturmasa"],
  ["community", "ನಮ್ಮ ಸಮಾಜ", "हमारा समाज", "Our Community"],
  ["panchakalyana", "ಪಂಚಕಲ್ಯಾಣ", "पंचकल्याण", "Panchakalyana"],
  ["weather", "ಹವಾಮಾನ", "मौसम", "Weather"],
].map(([slug, name_kn, name_hi, name_en], i) => ({
  id: id("tag", i + 1),
  slug,
  name_kn,
  name_en,
  name_hi,
  is_hidden_from_trending: false,
}));
const postTags = demoPosts.flatMap((p) => [
  {
    post_id: p.id,
    tag_id:
      tags[
        p.category_slugs.includes("basadi")
          ? 1
          : p.category_slugs.includes("chaturmasa")
            ? 2
            : p.category_slugs.includes("panchakalyana")
              ? 4
              : 3
      ].id,
  },
  { post_id: p.id, tag_id: tags[0].id },
]);
export const v4Demo: { [K in keyof DataTables]: DataTables[K][] } = {
  tags,
  places,
  post_tags: postTags,
  authors: [
    {
      id: "sample-author-desk",
      slug: "jwalamala-desk",
      name_kn: "ಜ್ವಾಲಾಮಾಲ ಸಂಪಾದಕೀಯ ತಂಡ",
      role_kn: "ಸಂಪಾದಕೀಯ ತಂಡ — ಮಾದರಿ",
      bio_kn: sample,
      credentials_kn: "ಲೇಖಕರ ವಿವರಗಳು ಪರಿಶೀಲನೆಯಲ್ಲಿವೆ.",
      name_en: "Jwalamala Editorial Team",
      role_en: "Editorial Team — Sample",
      bio_en: sampleEn,
      credentials_en: "Author details are still under review.",
      name_hi: "ज्वालामाल संपादकीय टीम",
      role_hi: "संपादकीय टीम — नमूना",
      bio_hi: sampleHi,
      credentials_hi: "लेखक का विवरण समीक्षाधीन है।",
      photo_url: null,
      is_active: true,
    },
  ],
  topics: [
    {
      id: id("topic", 1),
      slug: "jain-heritage",
      title_kn: "ನಮ್ಮ ಜೈನ ಪರಂಪರೆ",
      intro_kn: "ಬಸದಿಗಳು, ಇತಿಹಾಸ ಮತ್ತು ಸಂಸ್ಕೃತಿಯ ಕುರಿತ ಮಾದರಿ ವರದಿಗಳ ಸಂಗ್ರಹ.",
      title_en: "Our Jain Heritage",
      intro_en:
        "A collection of sample reports on Basadis, history and culture.",
      title_hi: "हमारी जैन परंपरा",
      intro_hi:
        "बसदियों, इतिहास और संस्कृति पर आधारित नमूना रिपोर्टों का संग्रह।",
      cover_url: "/images/temple.webp",
      key_facts: [
        "ಮಾದರಿ ವಿಷಯಗಳ ಸಂಗ್ರಹ",
        "ಸಂಬಂಧಿತ ಸುದ್ದಿಗಳು ಮತ್ತು ಕಾರ್ಯಕ್ರಮಗಳು",
      ],
      key_facts_en: [
        "A collection of sample topics",
        "Related news and events",
      ],
      key_facts_hi: ["नमूना विषयों का संग्रह", "संबंधित समाचार और कार्यक्रम"],
      tag_ids: [tags[1].id],
      timeline: [
        {
          date: "2026-09-14",
          text: "ಪರಂಪರೆ ಪರಿಚಯ — ಮಾದರಿ ವರದಿ",
          text_en: "An Introduction to Our Heritage — Sample Report",
          text_hi: "परंपरा का परिचय — नमूना रिपोर्ट",
        },
      ],
      event_ids: [demoEvents[0].id],
      liveblog_post_id: null,
      is_active: true,
      sort_order: 0,
    },
    {
      id: id("topic", 2),
      slug: "chaturmasa-2026",
      title_kn: "ಚಾತುರ್ಮಾಸ 2026",
      intro_kn: "ಪ್ರವಚನ, ಆತ್ಮಚಿಂತನೆ ಮತ್ತು ಸಮುದಾಯದ ಕಾರ್ಯಕ್ರಮಗಳ ಮಾದರಿ ಸಂಗ್ರಹ.",
      title_en: "Chaturmasa 2026",
      intro_en:
        "A sample collection of discourses, self-reflection and community programmes.",
      title_hi: "चातुर्मास 2026",
      intro_hi: "प्रवचन, आत्मचिंतन और समुदाय के कार्यक्रमों का नमूना संग्रह।",
      cover_url: "/images/detail.webp",
      key_facts: [sample],
      key_facts_en: [sampleEn],
      key_facts_hi: [sampleHi],
      tag_ids: [tags[2].id, tags[0].id],
      timeline: [],
      event_ids: [],
      liveblog_post_id: "sample-liveblog-1",
      is_active: true,
      sort_order: 1,
    },
    {
      id: id("topic", 3),
      slug: "community-stories",
      title_kn: "ನಮ್ಮ ಸಮಾಜದ ಕಥೆಗಳು",
      intro_kn: "ಶಿಕ್ಷಣ, ಸೇವೆ ಮತ್ತು ಸಾಧನೆಯ ಮಾದರಿ ಕಥೆಗಳು.",
      title_en: "Stories From Our Community",
      intro_en: "Sample stories of education, service and achievement.",
      title_hi: "हमारे समाज की कहानियाँ",
      intro_hi: "शिक्षा, सेवा और उपलब्धि की नमूना कहानियाँ।",
      cover_url: "/images/landscape.webp",
      key_facts: [sample],
      key_facts_en: [sampleEn],
      key_facts_hi: [sampleHi],
      tag_ids: [tags[3].id],
      timeline: [],
      event_ids: [demoEvents[1].id],
      liveblog_post_id: null,
      is_active: true,
      sort_order: 2,
    },
  ],
  topic_pins: [
    { topic_id: id("topic", 1), post_id: demoPosts[1].id, sort_order: 0 },
    { topic_id: id("topic", 2), post_id: demoPosts[2].id, sort_order: 0 },
  ],
  trending_items: [
    [
      "ನಮ್ಮ ಜೈನ ಪರಂಪರೆ",
      "/topic/jain-heritage",
      "topic",
      "हमारी जैन परंपरा",
      "Our Jain Heritage",
    ],
    ["ವಿಡಿಯೋ", "/videos", "page", "वीडियो", "Videos"],
    ["ಶಾರ್ಟ್ಸ್", "/shorts", "page", "शॉर्ट्स", "Shorts"],
    ["#ಅಹಿಂಸೆ", "/tag/ahimsa", "tag", "#अहिंसा", "#Ahimsa"],
    [
      "ಚಾತುರ್ಮಾಸ 2026",
      "/topic/chaturmasa-2026",
      "topic",
      "चातुर्मास 2026",
      "Chaturmasa 2026",
    ],
    ["ಹವಾಮಾನ", "/weather", "page", "मौसम", "Weather"],
    ["ಜೈನ ಪಂಚಾಂಗ", "/jain-calendar", "page", "जैन पंचांग", "Jain Calendar"],
    ["ಬಸದಿಗಳು", "/basadis", "page", "बसदियाँ", "Basadis"],
    ["ಅವಕಾಶಗಳು", "/opportunities", "page", "अवसर", "Opportunities"],
    [
      "ಸಮುದಾಯ ಪ್ರಕಟಣೆ",
      "/notices",
      "page",
      "समुदाय की सूचनाएँ",
      "Community Notices",
    ],
    ["ಚಿತ್ರಕಥೆಗಳು", "/stories", "page", "चित्रकथाएँ", "Web Stories"],
    ["ಹಾಸನ ಸುದ್ದಿ", "/place/hassan", "page", "हासन समाचार", "Hassan News"],
  ].map(([label_kn, url, type, label_hi, label_en], i) => ({
    id: id("trending", i + 1),
    label_kn,
    label_en,
    label_hi,
    url,
    type: type as "topic" | "page" | "tag",
    is_highlight: i === 0,
    starts_at: null,
    ends_at: null,
    sort_order: i,
    is_active: true,
  })),
  series: [
    {
      id: id("series", 1),
      slug: "chaturmasa-reflections",
      title_kn: "ಚಾತುರ್ಮಾಸ ಚಿಂತನೆ",
      description_kn: sample,
      title_en: "Chaturmasa Reflections",
      description_en: sampleEn,
      title_hi: "चातुर्मास चिंतन",
      description_hi: sampleHi,
      cover_url: "/images/detail.webp",
      is_active: true,
    },
    {
      id: id("series", 2),
      slug: "heritage-journey",
      title_kn: "ಪರಂಪರೆಯ ಪಯಣ",
      description_kn: sample,
      title_en: "A Journey Through Heritage",
      description_en: sampleEn,
      title_hi: "परंपरा की यात्रा",
      description_hi: sampleHi,
      cover_url: "/images/hill.webp",
      is_active: true,
    },
  ],
  series_items: demoPosts
    .filter((p) => p.type === "video")
    .map((p, i) => ({
      series_id: id("series", (i % 2) + 1),
      post_id: p.id,
      episode_no: Math.floor(i / 2) + 1,
    })),
  jain_calendar_days: Array.from({ length: 20 }, (_, i) => ({
    id: id("calendar", i + 1),
    date: `2026-${i < 15 ? "09" : "10"}-${String(i < 15 ? i + 16 : i - 14).padStart(2, "0")}`,
    title_kn: "ಪಂಚಾಂಗ ಟಿಪ್ಪಣಿ — ಮಾದರಿ",
    kind: "note",
    description_kn:
      "ಇದು ನೈಜ ತಿಥಿ ಅಥವಾ ಪರ್ವ ದಿನಾಂಕವಲ್ಲ. ಪರಿಶೀಲಿಸಿದ ಪಂಚಾಂಗವನ್ನು ಸಂಪಾದಕರು ಸೇರಿಸಬೇಕು.",
    title_en: "Calendar Note — Sample",
    description_en:
      "This is not a real tithi or festival date. A verified calendar is to be added by the editors.",
    title_hi: "पंचांग टिप्पणी — नमूना",
    description_hi:
      "यह वास्तविक तिथि या पर्व की तारीख नहीं है। सत्यापित पंचांग संपादकों द्वारा जोड़ा जाएगा।",
    is_major: false,
    is_seed: true,
  })),
  basadis: ["ಮೂಡುಬಿದಿರೆ", "ಶ್ರವಣಬೆಳಗೊಳ", "ಕಾರ್ಕಳ", "ಧರ್ಮಸ್ಥಳ", "ಹಾಸನ"].map(
    (name, i) => ({
      id: id("basadi", i + 1),
      slug: [
        "moodbidri",
        "shravanabelagola",
        "karkala",
        "dharmastala",
        "hassan",
      ][i],
      name_kn: name + " ಬಸದಿಯ ಪರಿಚಯ — ಮಾದರಿ",
      name_en:
        ["Moodbidri", "Shravanabelagola", "Karkala", "Dharmastala", "Hassan"][
          i
        ] + " Basadi: An Introduction — Sample",
      name_hi:
        ["मूडबिद्री", "श्रवणबेलगोला", "कारकल", "धर्मस्थल", "हासन"][i] +
        " बसदि का परिचय — नमूना",
      place_id:
        i === 0
          ? "sample-place-moodbidri"
          : i === 1
            ? "sample-place-shravana"
            : i === 2
              ? "sample-place-karkala"
              : i === 3
                ? "sample-place-dharmastala"
                : places.find((p) => p.slug === "hassan")!.id,
      deity_kn: "ವಿವರಗಳು ಪರಿಶೀಲನೆಯಲ್ಲಿವೆ",
      history_kn: sample,
      timings_kn: "ದರ್ಶನ ಸಮಯವನ್ನು ಸ್ಥಳೀಯ ಆಡಳಿತದಿಂದ ದೃಢಪಡಿಸಿಕೊಳ್ಳಿ.",
      deity_en: "Details under review",
      history_en: sampleEn,
      timings_en:
        "Please confirm darshan timings with the local basadi administration.",
      deity_hi: "विवरण समीक्षाधीन है",
      history_hi: sampleHi,
      timings_hi: "दर्शन का समय स्थानीय प्रबंधन से पुष्ट कर लें।",
      contact: "",
      lat: null,
      lng: null,
      photos: [
        {
          url: "/images/temple.webp",
          credit: "Wikimedia Commons — docs/ASSETS.md",
        },
      ],
      status: "published",
      is_seed: true,
    }),
  ),
  notices: Array.from({ length: 5 }, (_, i) => ({
    id: id("notice", i + 1),
    slug: "sample-notice-" + (i + 1),
    type:
      i === 0 ? "shraddhanjali" : i === 1 ? "student_achievement" : "amantrana",
    title_kn: [
      "ಶ್ರದ್ಧಾಂಜಲಿ ಪ್ರಕಟಣೆಯ ಮಾದರಿ",
      "ವಿದ್ಯಾರ್ಥಿ ಸಾಧನೆಯ ಮಾದರಿ ಪ್ರಕಟಣೆ",
      "ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮದ ಮಾದರಿ ಆಹ್ವಾನ",
      "ಸಮಾಜದ ಸಮಾಗಮ — ಮಾದರಿ",
      "ಸೇವಾ ಕಾರ್ಯಕ್ರಮ — ಮಾದರಿ",
    ][i],
    title_en: [
      "Sample Shraddhanjali Notice",
      "Sample Student Achievement Notice",
      "Sample Invitation to a Cultural Programme",
      "Community Gathering — Sample",
      "Service Programme — Sample",
    ][i],
    title_hi: [
      "श्रद्धांजलि सूचना का नमूना",
      "विद्यार्थी उपलब्धि की नमूना सूचना",
      "सांस्कृतिक कार्यक्रम का नमूना निमंत्रण",
      "समाज का समागम — नमूना",
      "सेवा कार्यक्रम — नमूना",
    ][i],
    person_name: "",
    photo_url: null,
    body_kn: sample,
    body_en: sampleEn,
    body_hi: sampleHi,
    place_id: places[3].id,
    event_date: "2026-09-24",
    contact: "",
    status: "approved",
    published_at: "2026-09-16T06:00:00Z",
    is_seed: true,
  })),
  opportunities: ["scholarship", "job", "competition"].map((kind, i) => ({
    id: id("opportunity", i + 1),
    slug: "sample-opportunity-" + (i + 1),
    title_kn: [
      "ವಿದ್ಯಾರ್ಥಿವೇತನ ಅವಕಾಶ — ಮಾದರಿ",
      "ಉದ್ಯೋಗ ಅವಕಾಶ — ಮಾದರಿ",
      "ಯುವ ಪ್ರತಿಭಾ ಸ್ಪರ್ಧೆ — ಮಾದರಿ",
    ][i],
    title_en: [
      "Scholarship Opportunity — Sample",
      "Job Opportunity — Sample",
      "Youth Talent Competition — Sample",
    ][i],
    title_hi: [
      "छात्रवृत्ति का अवसर — नमूना",
      "रोज़गार का अवसर — नमूना",
      "युवा प्रतिभा स्पर्धा — नमूना",
    ][i],
    org: "ಮಾದರಿ ಸಂಸ್ಥೆ",
    org_en: "Sample Organisation",
    org_hi: "नमूना संस्था",
    kind: kind as "scholarship" | "job" | "competition",
    place_id: places[3].id,
    last_date: "2026-12-31",
    link: null,
    contact: "",
    description_kn: sample,
    description_en: sampleEn,
    description_hi: sampleHi,
    status: "approved",
    is_seed: true,
  })),
  liveblogs: [
    {
      id: "sample-liveblog-1",
      slug: "community-live",
      title_kn: "ಸಮುದಾಯ ಸಮಾಗಮ: ನೇರ ವರದಿಯ ಮಾದರಿ",
      summary_kn: sample,
      title_en: "Community Gathering: A Sample Live Report",
      summary_en: sampleEn,
      title_hi: "समुदाय समागम: लाइव रिपोर्ट का नमूना",
      summary_hi: sampleHi,
      cover_url: "/images/landscape.webp",
      event_date: "2026-09-16",
      is_live: true,
      status: "published",
      published_at: "2026-09-16T06:00:00Z",
      is_seed: true,
    },
  ],
  liveblog_updates: Array.from({ length: 8 }, (_, i) => ({
    id: id("update", i + 1),
    liveblog_id: "sample-liveblog-1",
    body_html: `<p>ಮಾದರಿ ಅಪ್‌ಡೇಟ್ ${i + 1}: ಸಮುದಾಯ ಕಾರ್ಯಕ್ರಮದ ವರದಿ ಪ್ರಕಟವಾಗುವ ರೀತಿಯ ಪರಿಚಯ.</p>`,
    body_html_en: `<p>Sample update ${i + 1}: an introduction to the way a community event is reported here.</p>`,
    body_html_hi: `<p>नमूना अपडेट ${i + 1}: समुदाय के कार्यक्रम की रिपोर्ट किस तरह प्रकाशित होती है, इसका परिचय।</p>`,
    is_key: i === 7,
    is_pinned: i === 7,
    published_at: `2026-09-16T${String(6 + i).padStart(2, "0")}:00:00Z`,
    media: null,
  })),
  polls: [
    {
      id: id("poll", 1),
      question_kn: "ಯಾವ ವಿಷಯದ ಸುದ್ದಿಗಳನ್ನು ಹೆಚ್ಚು ಓದಲು ಬಯಸುತ್ತೀರಿ?",
      question_en: "Which subjects would you like to read more news about?",
      question_hi: "आप किस विषय के समाचार अधिक पढ़ना चाहेंगे?",
      options: ["ಬಸದಿಗಳ ಇತಿಹಾಸ", "ಪ್ರವಚನ", "ಸಮಾಜ ಸೇವೆ"],
      options_en: ["History of Basadis", "Discourses", "Community Service"],
      options_hi: ["बसदियों का इतिहास", "प्रवचन", "समाजसेवा"],
      ends_at: "2026-12-31T18:30:00Z",
      status: "active",
      is_seed: true,
    },
    {
      id: id("poll", 2),
      question_kn: "ನಿಮಗೆ ಯಾವ ರೂಪದ ವರದಿ ಇಷ್ಟ?",
      question_en: "Which format of reporting do you prefer?",
      question_hi: "आपको किस रूप की रिपोर्ट पसंद है?",
      options: ["ಲೇಖನ", "ವಿಡಿಯೋ", "ಕಿರುಸುದ್ದಿ"],
      options_en: ["Articles", "Videos", "News Briefs"],
      options_hi: ["लेख", "वीडियो", "संक्षिप्त समाचार"],
      ends_at: "2026-12-31T18:30:00Z",
      status: "active",
      is_seed: true,
    },
  ],
  quizzes: [
    {
      id: id("quiz", 1),
      slug: "reading-demo",
      title_kn: "ಓದುವ ಅನುಭವ — ಮಾದರಿ ರಸಪ್ರಶ್ನೆ",
      title_en: "The Reading Experience — Sample Quiz",
      title_hi: "पठन अनुभव — नमूना प्रश्नोत्तरी",
      questions: [
        {
          question: "ಸುದ್ದಿಯನ್ನು ನಂತರ ಓದಲು ಯಾವ ಆಯ್ಕೆ ಬಳಸಬೇಕು?",
          question_en: "Which option should you use to read a news item later?",
          question_hi:
            "समाचार को बाद में पढ़ने के लिए किस विकल्प का उपयोग करें?",
          options: ["ಉಳಿಸಿ", "ಹುಡುಕಿ", "ಹಂಚಿಕೊಳ್ಳಿ"],
          options_en: ["Save", "Search", "Share"],
          options_hi: ["सहेजें", "खोजें", "साझा करें"],
          answer: 0,
          explanation: "ಉಳಿಸಿ ಆಯ್ಕೆ ಲೇಖನವನ್ನು ಮತ್ತೆ ತೆರೆಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
          explanation_en:
            "The Save option lets you open the article again later.",
          explanation_hi:
            "सहेजें विकल्प लेख को बाद में दोबारा खोलने में मदद करता है।",
        },
        {
          question: "ಕಾರ್ಯಕ್ರಮಕ್ಕೆ ಹೋಗುವ ಮೊದಲು ಏನು ದೃಢಪಡಿಸಬೇಕು?",
          question_en: "What should you confirm before attending an event?",
          question_hi: "कार्यक्रम में जाने से पहले किसकी पुष्टि करनी चाहिए?",
          options: ["ಚಿತ್ರದ ಬಣ್ಣ", "ದಿನಾಂಕ ಮತ್ತು ಸ್ಥಳ", "ಪುಟದ ಗಾತ್ರ"],
          options_en: [
            "The colour of the photo",
            "The date and the venue",
            "The size of the page",
          ],
          options_hi: ["चित्र का रंग", "तारीख और स्थान", "पृष्ठ का आकार"],
          answer: 1,
          explanation: "ದಿನಾಂಕ ಮತ್ತು ಸ್ಥಳವನ್ನು ಆಯೋಜಕರಿಂದ ದೃಢಪಡಿಸಿಕೊಳ್ಳಿ.",
          explanation_en: "Confirm the date and the venue with the organisers.",
          explanation_hi: "तारीख और स्थान आयोजकों से पुष्ट कर लें।",
        },
      ],
      status: "published",
      is_seed: true,
    },
  ],
  galleries: [
    {
      id: id("gallery", 1),
      slug: "heritage-gallery",
      title_kn: "ಪರಂಪರೆಯ ನೋಟಗಳು",
      description_kn: sample,
      title_en: "Glimpses of Our Heritage",
      description_en: sampleEn,
      title_hi: "परंपरा की झलकियाँ",
      description_hi: sampleHi,
      images: ["hill", "temple", "detail"].map((name) => ({
        url: "/images/" + name + ".webp",
        caption: "ಪರಂಪರೆಯ ಚಿತ್ರ — ಮಾದರಿ ವಿನ್ಯಾಸ",
        caption_en: "A Heritage Photograph — Sample Layout",
        caption_hi: "परंपरा का चित्र — नमूना विन्यास",
        credit: "Wikimedia Commons — docs/ASSETS.md",
      })),
      event_date: "2026-09-14",
      status: "published",
      is_seed: true,
    },
  ],
  web_stories: [
    {
      id: id("story", 1),
      slug: "heritage-story",
      title_kn: "ಪರಂಪರೆಯ ಚಿತ್ರಕಥೆ",
      title_en: "A Heritage Web Story",
      title_hi: "परंपरा की चित्रकथा",
      cover_url: "/images/hill.webp",
      slides: ["hill", "temple", "detail", "landscape", "temple"].map(
        (name, i) => ({
          image: "/images/" + name + ".webp",
          text: "ನಮ್ಮ ಪರಂಪರೆ — ಮಾದರಿ ಚಿತ್ರಕಥೆ " + (i + 1),
          text_en: "Our Heritage — Sample Web Story " + (i + 1),
          text_hi: "हमारी परंपरा — नमूना चित्रकथा " + (i + 1),
          credit: "Wikimedia Commons — docs/ASSETS.md",
          href: "/topic/jain-heritage",
        }),
      ),
      status: "published",
      published_at: "2026-09-16T06:00:00Z",
      is_seed: true,
    },
  ],
  reservoir_readings: [
    {
      id: id("reservoir", 1),
      reservoir_slug: "sample",
      name_kn: "ಜಲಾಶಯ — ಮಾದರಿ",
      name_en: "Reservoir — Sample",
      name_hi: "जलाशय — नमूना",
      reading_date: "2026-09-16",
      full_level_m: 100,
      level_m: 60,
      storage_pct: 60,
      inflow_cusecs: 0,
      outflow_cusecs: 0,
      source: "ಮಾದರಿ ಅಂಕಿಗಳು; ನೈಜ ಜಲಾಶಯ ಮಾಹಿತಿ ಅಲ್ಲ.",
      source_en: "Sample figures; not real reservoir data.",
      source_hi: "नमूना आंकड़े; वास्तविक जलाशय की जानकारी नहीं।",
      is_seed: true,
    },
  ],
  market_rates: [],
  corrections_log: [],
};
