export const en = {
  home: "Home",
  videos: "Videos",
  search: "Search",
  events: "Events",
  account: "My account",
  news: "News",
  latest: "Latest news",
  allNews: "All news",
  allVideos: "All videos",
  allEvents: "All events",
  readMore: "Read more",
  watch: "Watch",
  live: "Live",
  breaking: "Headlines",
  featured: "Featured report",
  upcoming: "Upcoming events",
  trending: "Most read",
  community: "Our community · Our voice",
  tagline: "Light of truth. Voice of the community.",
  edition: "News for Karnataka’s Jain community",
  sendNews: "Send your news",
  sendTitle: "Your town’s stories belong here",
  sendDescription: "Share your community’s events, achievements and service.",
  subscribe: "Enable notifications",
  follow: "Stay connected",
  about: "About us",
  contact: "Contact",
  advertise: "Advertise",
  privacy: "Privacy",
  terms: "Terms",
  disclaimer: "Disclaimer",
  sample: "Sample edition",
  sampleNote: "These articles and events are design samples, not real news.",
  eventDate: "Event date",
  published: "Published date",
  place: "Place",
  readTime: "min read",
  searchPlaceholder: "Search news, places or events…",
  keyword: "Keyword",
  dateSearch: "Search by date",
  from: "From date",
  to: "To date",
  category: "Category",
  allCategories: "All categories",
  filter: "Search",
  clear: "Clear",
  noResults: "No stories found",
  tryAgain: "Try another word or date.",
  results: "Results",
  searchHint: "Search in Kannada or English, for example shravanabelagola.",
  save: "Save",
  saved: "Saved",
  share: "Share",
  copied: "Link copied",
  related: "Related stories",
  keyPoints: "Key points",
  backHome: "Back to home",
  next: "Next",
  previous: "Previous",
  noVideo: "A video has not been added to this sample article.",
  videoLabel: "Video report",
  login: "Login",
  loginTitle: "Welcome to our community",
  loginDescription: "Save stories and keep track of events that interest you.",
  phone: "Phone",
  phoneHint: "Include your country code, for example +91.",
  sendOtp: "Send OTP",
  otp: "6-digit OTP",
  verify: "Verify",
  google: "Continue with Google",
  skip: "Not now",
  unavailable: "This service is not available yet.",
  loginFailed: "Sign-in failed. Check your details and try again.",
  otpSent: "Code sent. Check your phone.",
  logout: "Logout",
  savedPosts: "Saved stories",
  reminders: "Reminders",
  interests: "Interests",
  notifications: "Notifications",
  noSaved: "No saved stories yet",
  remind: "Remind me",
  reminderSet: "Reminder saved",
  name: "Name",
  town: "Town",
  email: "Email",
  message: "Message",
  link: "Video or image link",
  submit: "Submit",
  submitting: "Submitting…",
  submitted: "Received for review. Thank you.",
  validation: "Please check the entered details.",
  required: "Required",
  offline: "You are offline",
  offlineDescription:
    "Previously opened stories may still be available. Reconnect to load new stories.",
  online: "Back online",
  retry: "Retry",
  install: "Install Jwalamala",
  installDescription: "Keep community news and events close at hand.",
  installButton: "Install",
  later: "Later",
  update: "An update is available",
  refresh: "Refresh",
  iosGuide: "In Safari, tap Share and choose Add to Home Screen.",
  dark: "Dark",
  light: "Light",
  menu: "Open menu",
  close: "Close",
  skipContent: "Skip to content",
  calendar: "Calendar",
  noEvents: "No events found",
  organiser: "Organiser",
  dateRange: "Date",
  eventDetails: "Event details",
  monthEvents: "This month’s events",
  footerText: "News, culture and community from Karnataka’s Jain society.",
  rights: "All rights reserved.",
  madeBy: "Created by",
  notFound: "Page not found",
  notFoundText: "The page you are looking for is unavailable.",
  error: "The page could not be shown",
  errorText: "Please try again.",
  admin: "Admin",
  dashboard: "Dashboard",
  posts: "Posts",
  categories: "Categories",
  submissions: "Submissions",
  import: "Import",
  users: "Users",
  settings: "Settings",
  newPost: "New post",
  title: "Title",
  draft: "Draft",
  publishedStatus: "Published",
  status: "Status",
  saveDraft: "Save draft",
  publish: "Publish",
  body: "Body",
  summary: "Summary",
  slug: "Slug",
  videoUrl: "Video link",
  primary: "Primary",
  subscribeSuccess: "Notifications enabled.",
  subscribeError:
    "Could not enable notifications. Check your browser permissions.",
  demoArticle:
    "This is sample content for design review, not a published news report.",
  imageCredit: "Image credit",
  explore: "Explore by category",
  all: "All",
  shorts: "Shorts",
  sort: "Sort",
  newest: "Newest",
  oldest: "Oldest",
  year: "Year",
  advertisement: "Advertisement",
  adSpace: "Space reserved for advertising",
  password: "Password",
  confirmPassword: "Re-enter password",
  showPassword: "Show password",
  hidePassword: "Hide password",
  passwordHint: "Use at least 8 characters.",
  passwordMismatch: "The passwords do not match.",
  appPasswordHint:
    "Use your Jwalamala account password. Never enter your Google password here.",
  or: "or",
  loginMethod: "Login method",
  emailLogin: "Email and password",
  phoneLogin: "Phone OTP",
  createAccount: "Create an account",
  forgotPassword: "Forgot password?",
  sendReset: "Send reset link",
  backToLogin: "Back to login",
  pleaseWait: "Please wait…",
  confirmEmailSent: "Check your email to confirm your account.",
  resetSent: "If an account exists, a reset link has been sent.",
  authRequestFailed: "Could not complete the request. Try again.",
  rateLimited:
    "Too many email/OTP requests right now. Please wait a few minutes and try again.",
  googleLoginFailed: "Could not start Google sign-in.",
  authLinkFailed: "This sign-in link is invalid or expired.",
  changePhone: "Change phone number",
  newPassword: "Set a new password",
  savePassword: "Save password",
  passwordUpdated: "Your password has been updated.",
  passwordUpdateFailed:
    "Could not update your password. Request a new reset link.",
  categoryNews: "News by category",
  commentsHeading: "Readers’ comments",
  commentsNote:
    "All comments appear after review. Please keep them respectful.",
  commentsLoadFailed: "Could not load comments. Please try again.",
  yourComment: "Your comment",
  sendForReview: "Send for review",
  commentReceived: "Received for review.",
  commentFailed: "Could not send your comment.",
  tryLater: "Please try again in a little while.",
  reportComment: "Report",
  reportSent: "Your report has been sent for review.",
  reportFailed: "Could not send the report.",
  reason: "Reason",
  send: "Send",
  connectionError: "Connection error.",
  termsAndRefund: "Terms and refund policy",
  agreeToTerms: "have been read and accepted.",
  oneTime: "one time",
  perMonth: "per month",
  perYear: "per year",
  billingCyclesNote:
    "billing cycles of automatic payments. You can cancel future payments from your account.",
  supportNow: "Support now",
  paymentConfirmed: "Payment confirmed. Thank you for your support.",
  paymentPending:
    "Your payment is being verified. Confirmed payments appear in your account.",
  paymentVerifyPending:
    "Payment verification is pending. Check your account before paying again.",
  paymentFailed:
    "The payment did not go through. Check the status in your account.",
  paymentStartFailed:
    "Could not start the payment. If you already have a membership, check your account.",
  paymentServiceUnavailable: "The payment service is unavailable.",
  notificationTopics: "Topics",
  notificationsAllDevices: "Notifications on all devices",
  dailyMax: "Daily maximum",
  quietStart: "Quiet hours start (IST)",
  quietEnd: "Quiet hours end (IST)",
  breakingOverride: "Allow breaking news during quiet hours",
  stopOnDevice: "Stop on this device",
  pushStoppedDevice: "Notifications have been stopped on this device.",
  state: "State",
  district: "District",
  cityOrTown: "City / town",
  karnataka: "Karnataka",
  selectStateFirst: "Select a state first",
  selectDistrictFirst: "Select a district first",
  noCities: "No cities added yet",
  membership: "Membership",
  cancelSupportNote:
    "You can cancel future automatic payments. The benefits of the period you have already paid for continue.",
  cancelRenewal: "Cancel renewal",
  confirmStopPayments: "Yes, stop future payments",
  renewalCancelled: "Future payments have been cancelled.",
  cancelFailed: "Could not cancel. Please contact us.",
  sponsorApproved: "Approved. Editors decide on the final publication.",
  sponsorApprovalIntro:
    "You are reviewing and approving this version on behalf of the sponsor.",
  approveVersion: "Approve this version",
  sponsorLinkExpired:
    "The version has changed or the link has expired. Request a new link.",
  openVideo: "Open video",
  resumeAt: "Resume at",
  startOver: "Start over",
  videoChapters: "Video chapters",
  cancelReminder: "Cancel reminder",
  notificationSettings: "Notification settings",
  continueWatching: "Continue watching",
  featuredPhoto: "Featured photograph",
  onThisDay: "On this day",
  loadingContent: "Loading content…",
  closeAd: "Close advertisement",
  totalChoices: "Total choices",
  preferredSourceNote: "Choose Jwalamala as a preferred source on Google.",
  condolenceMessages: "Condolence messages",
  messagesAfterReview: "Messages are published after review.",
  readInKannada: "Read in Kannada",
  readInEnglish: "Read in English",
  readInHindi: "Read in Hindi",
  machineTranslated: "Machine translated from Kannada, not yet reviewed",
  sponsoredContent: "Sponsored content",
  contributorApplication: "Citizen reporter application",
  contributorIntro:
    "Sign in using a verified phone OTP, then apply. An administrator reviews your application and assigns your reporting area. Contributions are saved as drafts for editorial review.",
  reportingArea: "Reporting area",
  yourExperience: "Your experience",
  applyNow: "Apply",
  applicationSent: "Application sent for review.",
  submitFailed: "Unable to submit.",
  contributorDetailsNeeded:
    "Select a place and describe your reporting experience.",
  contributorPhoneNeeded:
    "Phone OTP verification is required. Check your details and try again.",
  earlyAccess: "Early access for supporters",
  noEarlyAccess: "No early-access stories are available for your account.",
  supportBrand: "Support {brand}",
  supportIntro: "Your support for our community newsroom.",
  payee: "Payments received by",
  mySupportAndPayments: "My support and payments",
  supportPaymentsNotLive:
    "Online support payments have not started yet. For details",
  contactUs: "contact us",
  supportTerms: "Support terms",
  refundPolicy: "Refund policy",
  contactLabel: "Contact",
  supportTermsPending:
    "The terms will be published here before the payment service begins.",
  mySupport: "My support",
  supporterActiveUntil: "Supporter · active until {date}",
  paymentHistory: "Payment history",
  date: "Date",
  amount: "Amount",
  paymentId: "Payment ID",
  paymentCaptured: "Confirmed",
  refunded: "Refunded",
  noPayments: "No confirmed payments.",
  citizenReporter: "Citizen reporter",
  earlyAccessShort: "Early access",
  fullScreenStory: "Full-screen story",
  newsNearYou: "News near you",
  editorPicks: "Editors’ picks",
  pages: "Pages",
  siteLanguage: "Site language",
};
export const v4en = {
  liveReaders: "Readers right now",
  analyticsWindow:
    "Anonymous sessions seen in the last 5 minutes. Activity on sample content is not counted.",
  views: "Views",
  engagedSeconds: "Seconds of active reading",
  shares: "Shares",
  listens: "Listens",
  refresh: "Refresh",
  title: "Title",
  campaigns: "Campaigns",
  legacySlot: "Original ad placement",
  image: "Image",
  mobileImage: "Mobile image link",
  alt: "Alt",
  adSlots: "Ad placements",
  targetPages: "Page types — one per line",
  device: "Device",
  weight: "Weight",
  impressionCap: "Total impression cap",
  clickCap: "Total click cap",
  dailyCap: "Daily impression cap",
  sponsored: "Sponsored",
  adCspReady: "The ad security configuration is ready.",
  adCspMissing: "Real Google ads need ADS_STRICT_CSP=true set on the server.",
  format: "Format",
  creatives: "Creatives",
  adReport: "Ad report",
  impressions: "Impressions",
  clicks: "Clicks",
  deskHint:
    "Move reports through the desk stages. Changing a stage in this panel does not publish the report automatically.",
  unassigned: "Unassigned",
  assignee: "Assignee",
  priority: "Priority",
  paragraph: "Paragraph number (the first is 0)",
  checkInbox: "Check the confirmation link sent to your email.",
  newsletterHint:
    "Get the newsletter of your choice by email. The subscription starts only after you confirm it, and you can stop it at any time.",
  frequency: "Frequency",
  weekly: "Weekly",
  daily: "Daily",
  confirmNewsletter: "Confirm your email subscription",
  subscriptionConfirmed: "Your subscription has been confirmed.",
  unsubscribed: "Your subscription has been stopped.",
  linkExpired: "This link has expired or has already been used.",
  providerDisabled:
    "The service is disabled or its usage limit has been reached.",
  aiSensitive: "AI suggestions are disabled for this category.",
  aiSuggestion: "AI suggestion",
  aiReview:
    "Review the suggestions. After using one, save the report separately.",
  generate: "Generate",
  accepted: "Accepted",
  budgetNote:
    "Providers are disabled until you enable them and set a monthly usage limit.",
  credentialsReady: "The service keys have been set",
  credentialsMissing: "The service keys are still needed",
  usage: "Usage this month",
  monthlyLimit: "Monthly usage limit",
  aiBlockedCategories: "Categories with AI disabled",
  role: "Role",
  roles: "Roles and permissions",
  embargo: "Embargo time (IST)",
  quickSummary: "Short highlights — one per line",
  hideAds: "Hide ads on this article",
  meaningfulEdit: "Significant correction readers should be told about",
  locked: "Another editor is editing this report.",
  restore: "Restore as a draft",
  reviewNote: "Review note",
  publishChecklist:
    "Before publishing: title up to 110 characters, summary, event date, image credit and primary category are required.",
  samplePoll: "Sample poll — only to test how your choice is recorded.",
  localOnly: "Recorded on this device only.",
  voteFailed:
    "Your vote could not be recorded. Voting may have closed, or you may have already voted.",
  totalVotes: "Total votes",
  showScore: "See the result",
  tryAgain: "Try again",
  questions: "Questions",
  reactions: "Reactions",
  namana: "Namana",
  useful: "Useful",
  sad: "Sad",
  thankYou: "Thank you",
  waterLevel: "Water level",
  recentReadings: "Recent readings",
  noVerifiedData: "Verified data is not available yet.",
  rateDisclaimer:
    "Rates follow the published source and date. Local market rates may differ.",
  price: "Price",
  organization: "Organisation",
  feed: "Feed",
  syncFailed:
    "Could not sync your data with your account. It has been saved locally.",
  edit: "Edit",
  select: "Select",
  answerNumberHint:
    "Number of the correct answer: the first option is 0, the second is 1.",
  latitude: "Latitude",
  longitude: "Longitude",
  credentials: "Qualifications and experience",
  deity: "Deity",
  options: "Options",
  fullLevel: "Full level (m)",
  currentLevel: "Today’s level (m)",
  inflow: "Inflow",
  outflow: "Outflow",
  value: "Value",
  unit: "Unit",
  addRow: "Add a row",
  remove: "Remove",
  caption: "Caption",
  note: "Note",
  question: "Question",
  answer: "Answer",
  explanation: "Explanation",
  nearMe: "Near me",
  savedPlace: "Saved town",
  locationFailed:
    "Could not find your location. Choose your town from the list.",
  rain: "Rain",
  weatherAvailability:
    "Verified weather data will be published here once it is available.",
  aqiNote:
    "This is a model-based estimate, not a reading from an official station. The index uses the available 24-hour PM2.5, PM10, NO₂ and SO₂ averages.",
  contentType: "Type of content",
  trendingTopics: "Trending now",
  topics: "Topics",
  tags: "Tags",
  popularTags: "Popular tags",
  places: "Places",
  authors: "Authors",
  series: "Series",
  episodes: "Episodes",
  keyFacts: "Key facts",
  timeline: "Timeline",
  pinned: "Pinned",
  archive: "Archive",
  allTopics: "All topics",
  weather: "Weather",
  jainCalendar: "Jain calendar",
  dailyTimes: "Today’s timings",
  sunrise: "Sunrise",
  sunset: "Sunset",
  timeNote: "Times are approximate. Consult your local calendar.",
  observancePending:
    "Religious observance offsets await review by a community advisor. Only astronomical sunrise and sunset are shown.",
  choosePlace: "Choose a town",
  changePlace: "Change town",
  updated: "Updated",
  source: "Source",
  stale: "Stale",
  noWeather: "Weather is not available for this place yet.",
  forecast: "Forecast for the coming days",
  hourly: "Hourly",
  temperature: "Temperature",
  humidity: "Humidity",
  wind: "Wind",
  feelsLike: "Feels like",
  airQuality: "Air quality",
  estimated: "Estimated",
  dataUnavailable: "Data not yet available",
  noCalendar: "Verified calendar entries have not been added for this month.",
  basadis: "Basadi directory",
  notices: "Community notices",
  opportunities: "Opportunities",
  district: "District",
  timings: "Timings",
  map: "Map",
  relatedNews: "Related news",
  obituary: "In memoriam",
  submitNotice: "Send a notice",
  submitOpportunity: "Send details of an opportunity",
  deadline: "Deadline",
  organisation: "Organisation",
  apply: "View details",
  job: "Job",
  scholarship: "Scholarship",
  competition: "Competition",
  admission: "Admission",
  gallery: "Gallery",
  stories: "Web stories",
  liveblogs: "Live reports",
  liveblog: "Liveblog",
  newUpdates: "New updates",
  loadUpdates: "Show the new updates",
  ended: "Live report ended",
  polls: "Polls",
  vote: "Vote",
  pollClosed: "Voting has ended",
  pollSaved: "Your vote was recorded",
  sampleVote: "This is a sample poll. Results are stored only on this device.",
  quizzes: "Quizzes",
  checkAnswer: "Check the answer",
  score: "Score",
  restart: "Restart",
  reservoirs: "Reservoir water levels",
  rates: "Today’s rates",
  storage: "Storage",
  rateGold22: "Gold 22K",
  rateGold24: "Gold 24K",
  rateSilver: "Silver",
  ratePetrol: "Petrol",
  rateDiesel: "Diesel",
  readingTools: "Reading options",
  textSize: "Text size",
  lineSpace: "Line spacing",
  contrast: "Contrast",
  print: "Print",
  listen: "Listen to this article",
  pause: "Pause",
  resume: "Resume",
  stop: "Stop",
  readingTime: "Reading time",
  minutes: "Minutes",
  follow: "Follow",
  following: "Following",
  localFollow: "Saved on this device. Sign in to sync.",
  myFeed: "For you",
  history: "Reading history",
  clearHistory: "Clear the history",
  newsletter: "Newsletter",
  subscribe: "Subscribe",
  unsubscribe: "Unsubscribe",
  newsletterNote:
    "Confirm your subscription using the link sent to your email.",
  channels: "Channels",
  editorial: "Editorial",
  corrections: "Corrections",
  factcheck: "Factcheck",
  ownership: "Ownership and finances",
  trustDraft:
    "This is a draft policy. The final policy will be published after the organisation has reviewed and approved it.",
  credit: "Image credit",
  nextEpisode: "Next episode",
  previousStory: "Previous story",
  nextStory: "Next story",
  desk: "Desk",
  review: "Review",
  versions: "Versions",
  assistant: "Assistant",
  analytics: "Analytics",
  social: "Social",
  providers: "Providers",
  budgets: "Budgets",
  moderation: "Moderation",
  pending: "Pending",
  approved: "Approved",
  reject: "Reject",
  approve: "Approve",
  draft: "Draft",
  publish: "Publish",
  saveDraft: "Save draft",
  suggestions: "Suggestions",
  accept: "Accept",
  enabled: "Enabled",
  disabled: "Disabled",
  start: "Start",
  end: "End",
  order: "Order",
  hide: "Hide",
  merge: "Merge",
  newItem: "New entry",
  saved: "Saved",
  failed: "Could not complete the request. Please try again.",
  serviceOff: "This service is not enabled yet.",
  sample: "Sample",
  readingHistoryEmpty: "Stories you have read will appear here.",
  noFollow: "Follow topics to see their latest stories here.",
  support: "Support Jwalamala",
  paymentsUnavailable: "Support payments are not available yet.",
  openMenu: "Open all sections",
  closeMenu: "Close sections",
  more: "More",
  liveSample: "Sample live report",
  shareWhatsApp: "Share on WhatsApp",
  clear: "Clear",
  loading: "Loading",
  shorts: "Shorts",
  read: "Read",
  homeSections: "Home page sections",
  adManager: "Ad management",
  import: "Import",
  report: "Report",
  exportCsv: "Download CSV",
  settings: "Settings",
  up: "Up",
  down: "Down",
  theme: "Appearance",
  systemTheme: "System",
  correctionsIntro:
    "Significant corrections and clarifications to published reports are recorded here. Contact us if you spot an error in a report.",
  noCorrections: "No corrections have been published yet.",
  editorialPolicy: "Editorial policy",
  factCheckPolicy: "Fact-check policy",
  captionTooLong: "The message is too long. Select fewer reports.",
  distributionReview:
    "Create a draft from selected published reports. Review the full message and approve it for sending.",
  network: "Network",
  createDraft: "Create draft",
  queued: "Added to the sending queue.",
  approveAndQueue: "Approve and queue for sending",
  channelId: "Page / channel ID",
  accessToken: "Service access token",
  activeSubscribers: "Confirmed subscribers",
  jobs: "Background jobs",
  status: "Status",
  attempts: "Attempts",
  audioPlayFailed: "Audio could not be played.",
  audioProgress: "Audio progress",
  audioSpeed: "Playback speed",
  next6Hours: "next 6 hours",
  localShops: "Local shops",
  districtNews: "District-wise news",
  districtNewsIntro:
    "News, reports and programmes from every district of Karnataka, in one place.",
  allDistricts: "All districts",
  findDistrict: "Find a district",
  noDistrictMatch: "No district matches that name.",
  districtLatest: "Latest from the district",
  districtAllNews: "All news from this district",
  noDistrictNews: "No news has been published from this district yet.",
  districtTowns: "Towns in this district",
  otherDistricts: "Other districts",
};
export const monthsEn = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export const weekdaysEn = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const aqiLabelsEn = [
  "Good",
  "Satisfactory",
  "Moderate",
  "Poor",
  "Very poor",
  "Severe",
] as const;
export const weatherLabelsEn: Record<string, string> = {
  "0": "Clear sky",
  "1": "Mainly clear",
  "2": "Partly cloudy",
  "3": "Overcast",
  "45": "Fog",
  "48": "Fog",
  "51": "Light drizzle",
  "53": "Drizzle",
  "55": "Heavy drizzle",
  "61": "Light rain",
  "63": "Rain",
  "65": "Heavy rain",
  "71": "Light snow",
  "73": "Snow",
  "75": "Heavy snow",
  "80": "Rain showers",
  "81": "Rain",
  "82": "Heavy rain",
  "95": "Thunderstorm",
};
export const pushLabelsEn: Record<string, string> = {
  breaking: "Breaking news",
  live: "Live coverage",
  daily: "Top story of the day",
  events: "Events",
  parva: "Jain parvas",
};
