import { en, v4en as t } from "./strings.en";
import { site } from "@/config/site";
export const pagesEn: Record<string, { title: string; paragraphs: string[] }> =
  {
    "editorial-policy": {
      title: t.editorialPolicy,
      paragraphs: [
        "Every report keeps the date on which the event happened clearly separate from the date of publication. Verifying sources, names, places and image credits before publication is an editorial responsibility.",
        "Announcements sent in by readers appear publicly only after they have been checked. Sponsored content must be clearly identified. Suggestions generated by AI require an editor’s review.",
        "If you spot an error in a report, send us the link to the original report along with the evidence for the correct information through the contact page.",
      ],
    },
    "fact-check-policy": {
      title: t.factCheckPolicy,
      paragraphs: [
        "A claim that needs checking must be tested against primary records and confirmation from the people concerned. A detail that has not been confirmed must not be published as settled fact.",
        "The timings and dates of religious observances require verification by the community’s recognised advisers. If you have a question about a source or a correction, contact us.",
      ],
    },
    ownership: {
      title: t.ownership,
      paragraphs: [
        "The publisher’s legal ownership, editorial responsibility and financial details have not been published yet. Please use the contact page to ask for this information.",
      ],
    },
    about: {
      title: en.about,
      paragraphs: [
        `${site.englishName} is a platform devoted to the news and culture of Karnataka’s Jain community. Our purpose is to present the community’s events, achievements, heritage and values of life in Kannada.`,
        en.footerText,
        en.sampleNote,
      ],
    },
    privacy: {
      title: en.privacy,
      paragraphs: [
        "This is a pre-launch sample edition. The organisation’s contact details and the final privacy policy will be added before the service opens to the public.",
        "Once the account service is live, the information needed for signing in and for saved stories will be used. Notifications are switched on only after you give permission. Playing a video creates a connection to the relevant external service.",
        "Limited information may be stored on this device for the install prompt and for offline reading. You can clear it through your browser settings.",
        "Advertising: third-party vendors, including Google, use cookies to serve ads based on your prior visits to this and other websites. You can opt out of personalised advertising at adssettings.google.com; see policies.google.com/technologies/ads for details.",
        "Views and clicks on our direct ads are counted against a hashed device identifier only; your name and contact details are never shared with advertisers. Contact details sent with an advertising application are used only for review and billing.",
      ],
    },
    terms: {
      title: en.terms,
      paragraphs: [
        "The content in this edition is for display only. Do not use it as confirmation of real news or of an event.",
        "Submit only content that is your own or that you have permission to share. Editorial review takes place before publication. The final terms of use will be published before the public release.",
      ],
    },
    disclaimer: {
      title: en.disclaimer,
      paragraphs: [
        en.sampleNote,
        "Videos belong to the YouTube or Facebook publishers concerned. Before setting out for an event, confirm the date and the venue with the organisers.",
      ],
    },
  };
