export const kn = {
  home: "ಮುಖಪುಟ",
  videos: "ವಿಡಿಯೋಗಳು",
  search: "ಹುಡುಕಿ",
  events: "ಕಾರ್ಯಕ್ರಮಗಳು",
  account: "ನನ್ನ ಖಾತೆ",
  news: "ಸುದ್ದಿಗಳು",
  latest: "ಇತ್ತೀಚಿನ ಸುದ್ದಿಗಳು",
  allNews: "ಎಲ್ಲಾ ಸುದ್ದಿಗಳು",
  allVideos: "ಎಲ್ಲಾ ವಿಡಿಯೋಗಳು",
  allEvents: "ಎಲ್ಲಾ ಕಾರ್ಯಕ್ರಮಗಳು",
  readMore: "ಮುಂದೆ ಓದಿ",
  watch: "ವಿಡಿಯೋ ವೀಕ್ಷಿಸಿ",
  live: "ನೇರಪ್ರಸಾರ",
  breaking: "ಮುಖ್ಯಾಂಶಗಳು",
  featured: "ವಿಶೇಷ ವರದಿ",
  upcoming: "ಮುಂಬರುವ ಕಾರ್ಯಕ್ರಮಗಳು",
  trending: "ಹೆಚ್ಚು ಓದಿದ ಸುದ್ದಿಗಳು",
  community: "ನಮ್ಮ ಸಮಾಜ · ನಮ್ಮ ಧ್ವನಿ",
  tagline: "ಸತ್ಯದ ಬೆಳಕು. ಸಮಾಜದ ಧ್ವನಿ.",
  edition: "ಕರ್ನಾಟಕದ ಜೈನ ಸಮುದಾಯದ ಸುದ್ದಿತಾಣ",
  sendNews: "ನಿಮ್ಮ ಸುದ್ದಿ ಕಳುಹಿಸಿ",
  sendTitle: "ನಿಮ್ಮ ಊರಿನ ಸುದ್ದಿಗೆ ನಮ್ಮಲ್ಲಿ ಜಾಗವಿದೆ",
  sendDescription:
    "ಕಾರ್ಯಕ್ರಮ, ಸಾಧನೆ, ಸಮಾಜಸೇವೆ — ನಿಮ್ಮ ಸಮುದಾಯದ ಕಥೆಯನ್ನು ನಮ್ಮೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ.",
  subscribe: "ಅಧಿಸೂಚನೆ ಪಡೆಯಿರಿ",
  follow: "ನಮ್ಮೊಂದಿಗೆ ಸಂಪರ್ಕದಲ್ಲಿರಿ",
  about: "ನಮ್ಮ ಬಗ್ಗೆ",
  contact: "ಸಂಪರ್ಕಿಸಿ",
  advertise: "ಜಾಹೀರಾತು",
  privacy: "ಗೌಪ್ಯತೆ",
  terms: "ನಿಯಮಗಳು",
  disclaimer: "ಹಕ್ಕು ನಿರಾಕರಣೆ",
  sample: "ಮಾದರಿ ಆವೃತ್ತಿ",
  sampleNote:
    "ಇಲ್ಲಿನ ಲೇಖನಗಳು ಮತ್ತು ಕಾರ್ಯಕ್ರಮಗಳು ವಿನ್ಯಾಸದ ಮಾದರಿಗಳು; ನೈಜ ಸುದ್ದಿಗಳಲ್ಲ.",
  eventDate: "ಕಾರ್ಯಕ್ರಮ ದಿನಾಂಕ",
  published: "ಪ್ರಕಟಿತ ದಿನಾಂಕ",
  place: "ಸ್ಥಳ",
  readTime: "ನಿಮಿಷ ಓದು",
  searchPlaceholder: "ಸುದ್ದಿ, ಸ್ಥಳ ಅಥವಾ ಕಾರ್ಯಕ್ರಮ ಹುಡುಕಿ…",
  keyword: "ಕೀವರ್ಡ್",
  dateSearch: "ದಿನಾಂಕದ ಮೂಲಕ",
  from: "ಆರಂಭ ದಿನಾಂಕ",
  to: "ಅಂತಿಮ ದಿನಾಂಕ",
  category: "ವರ್ಗ",
  allCategories: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
  filter: "ಹುಡುಕಿ",
  clear: "ತೆರವುಗೊಳಿಸಿ",
  noResults: "ಯಾವುದೇ ಸುದ್ದಿ ಸಿಗಲಿಲ್ಲ",
  tryAgain: "ಬೇರೆ ಪದ ಅಥವಾ ದಿನಾಂಕದೊಂದಿಗೆ ಮತ್ತೆ ಹುಡುಕಿ.",
  results: "ಫಲಿತಾಂಶಗಳು",
  searchHint:
    "ಕನ್ನಡ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಹುಡುಕಿ. ಉದಾ: ಶ್ರವಣಬೆಳಗೊಳ / shravanabelagola",
  save: "ಉಳಿಸಿ",
  saved: "ಉಳಿಸಲಾಗಿದೆ",
  share: "ಹಂಚಿಕೊಳ್ಳಿ",
  copied: "ಲಿಂಕ್ ನಕಲಿಸಲಾಗಿದೆ",
  related: "ಇದನ್ನೂ ಓದಿ",
  keyPoints: "ಪ್ರಮುಖ ಅಂಶಗಳು",
  backHome: "ಮುಖಪುಟಕ್ಕೆ",
  next: "ಮುಂದೆ",
  previous: "ಹಿಂದೆ",
  noVideo: "ಈ ಮಾದರಿ ಲೇಖನಕ್ಕೆ ವಿಡಿಯೋ ಇನ್ನೂ ಸೇರಿಸಿಲ್ಲ.",
  videoLabel: "ವಿಡಿಯೋ ವರದಿ",
  login: "ಲಾಗಿನ್",
  loginTitle: "ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಸ್ವಾಗತ",
  loginDescription:
    "ಸುದ್ದಿಗಳನ್ನು ಉಳಿಸಿ. ನಿಮ್ಮ ಆಸಕ್ತಿಯ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ನೆನಪಿಟ್ಟುಕೊಳ್ಳಿ.",
  phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
  phoneHint: "+91 ಸೇರಿದಂತೆ ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
  sendOtp: "ಒಟಿಪಿ ಕಳುಹಿಸಿ",
  otp: "6 ಅಂಕಿಯ ಒಟಿಪಿ",
  verify: "ಪರಿಶೀಲಿಸಿ",
  google: "Google ಮೂಲಕ ಮುಂದುವರಿಸಿ",
  skip: "ಈಗ ಬೇಡ",
  unavailable: "ಈ ಸೇವೆ ಇನ್ನೂ ಸಿದ್ಧವಾಗುತ್ತಿದೆ. ಶೀಘ್ರದಲ್ಲೇ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  loginFailed: "ಲಾಗಿನ್ ಆಗಲಿಲ್ಲ. ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
  otpSent: "ನಿಮ್ಮ ಮೊಬೈಲ್‌ಗೆ ಒಟಿಪಿ ಕಳುಹಿಸಲಾಗಿದೆ.",
  logout: "ಲಾಗ್ ಔಟ್",
  savedPosts: "ಉಳಿಸಿದ ಸುದ್ದಿಗಳು",
  reminders: "ಕಾರ್ಯಕ್ರಮ ಜ್ಞಾಪನೆಗಳು",
  interests: "ನನ್ನ ಆಸಕ್ತಿಗಳು",
  notifications: "ಅಧಿಸೂಚನೆಗಳು",
  noSaved: "ಇನ್ನೂ ಯಾವುದೇ ಸುದ್ದಿ ಉಳಿಸಿಲ್ಲ.",
  remind: "ನನಗೆ ನೆನಪಿಸಿ",
  reminderSet: "ಜ್ಞಾಪನೆ ಸೇರಿಸಲಾಗಿದೆ",
  name: "ನಿಮ್ಮ ಹೆಸರು",
  town: "ಊರು",
  email: "ಇಮೇಲ್",
  message: "ಸುದ್ದಿಯ ವಿವರ",
  link: "ವಿಡಿಯೋ ಅಥವಾ ಚಿತ್ರದ ಲಿಂಕ್",
  submit: "ಸುದ್ದಿ ಕಳುಹಿಸಿ",
  submitting: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…",
  submitted: "ಧನ್ಯವಾದಗಳು. ನಿಮ್ಮ ಸುದ್ದಿ ತಲುಪಿದೆ.",
  validation: "ಎಲ್ಲಾ ಅಗತ್ಯ ವಿವರಗಳನ್ನು ಸರಿಯಾಗಿ ತುಂಬಿ.",
  required: "ಅಗತ್ಯ",
  offline: "ನೀವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ",
  offlineDescription:
    "ಈಗ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ. ಹಿಂದೆ ತೆರೆದ ಸುದ್ದಿಗಳನ್ನು ಓದಬಹುದು. ಸಂಪರ್ಕ ಬಂದಾಗ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  online: "ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಬಂದಿದೆ",
  retry: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
  install: "ಆ್ಯಪ್ ಆಗಿ ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿ",
  installDescription: "ಸುದ್ದಿ ಮತ್ತು ಕಾರ್ಯಕ್ರಮಗಳು ಈಗ ನಿಮ್ಮ ಬೆರಳ ತುದಿಯಲ್ಲಿ.",
  installButton: "ಇನ್‌ಸ್ಟಾಲ್",
  later: "ನಂತರ",
  update: "ಹೊಸ ಆವೃತ್ತಿ ಲಭ್ಯವಿದೆ",
  refresh: "ರಿಫ್ರೆಶ್",
  iosGuide: "Safari ಹಂಚಿಕೆ ಬಟನ್ ಒತ್ತಿ, ‘Add to Home Screen’ ಆಯ್ಕೆಮಾಡಿ.",
  dark: "ಕತ್ತಲೆ ನೋಟ",
  light: "ಬೆಳಕಿನ ನೋಟ",
  menu: "ಮೆನು ತೆರೆಯಿರಿ",
  close: "ಮುಚ್ಚಿ",
  skipContent: "ಮುಖ್ಯ ವಿಷಯಕ್ಕೆ ಹೋಗಿ",
  calendar: "ಕಾರ್ಯಕ್ರಮ ಕ್ಯಾಲೆಂಡರ್",
  noEvents: "ಈ ದಿನ ಯಾವುದೇ ಕಾರ್ಯಕ್ರಮವಿಲ್ಲ.",
  organiser: "ಆಯೋಜಕರು",
  dateRange: "ದಿನಾಂಕ",
  eventDetails: "ಕಾರ್ಯಕ್ರಮದ ವಿವರ",
  monthEvents: "ಈ ತಿಂಗಳ ಕಾರ್ಯಕ್ರಮಗಳು",
  footerText:
    "ಜೈನ ಸಮಾಜದ ಸುದ್ದಿ, ಪರಂಪರೆ, ಸಾಧನೆ ಮತ್ತು ಸಂಸ್ಕೃತಿಯನ್ನು ನಿಮ್ಮ ಬಳಿಗೆ ತರುವ ವಿಶ್ವಾಸದ ವೇದಿಕೆ.",
  rights: "ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
  madeBy: "ವಿನ್ಯಾಸ ಮತ್ತು ಅಭಿವೃದ್ಧಿ: MyDesignNexus",
  notFound: "ಈ ಪುಟ ಸಿಗಲಿಲ್ಲ",
  notFoundText: "ಲಿಂಕ್ ಬದಲಾಗಿರಬಹುದು. ಮುಖಪುಟದಿಂದ ಮತ್ತೆ ಆರಂಭಿಸಿ.",
  error: "ಪುಟವನ್ನು ತೋರಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",
  errorText: "ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  admin: "ಸಂಪಾದಕೀಯ",
  dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  posts: "ಲೇಖನಗಳು",
  categories: "ವರ್ಗಗಳು",
  submissions: "ಸಲ್ಲಿಕೆಗಳು",
  import: "ಆಮದು",
  users: "ಬಳಕೆದಾರರು",
  settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
  newPost: "ಹೊಸ ಲೇಖನ",
  title: "ಶೀರ್ಷಿಕೆ",
  draft: "ಕರಡು",
  publishedStatus: "ಪ್ರಕಟಿತ",
  status: "ಸ್ಥಿತಿ",
  saveDraft: "ಕರಡು ಉಳಿಸಿ",
  publish: "ಪ್ರಕಟಿಸಿ",
  body: "ಲೇಖನದ ವಿಷಯ",
  summary: "ಸಾರಾಂಶ",
  slug: "ಪುಟದ ವಿಳಾಸ",
  videoUrl: "ವಿಡಿಯೋ ಲಿಂಕ್",
  primary: "ಮುಖ್ಯ ವರ್ಗ",
  subscribeSuccess: "ಅಧಿಸೂಚನೆಗಳಿಗೆ ನೋಂದಾಯಿಸಲಾಗಿದೆ",
  subscribeError: "ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
  demoArticle:
    "ಇದು ಮಾದರಿ ಲೇಖನ. ಇಲ್ಲಿ ನೀಡಿರುವ ಕಾರ್ಯಕ್ರಮದ ವಿವರಗಳು ನೈಜ ಪ್ರಕಟಣೆಯಲ್ಲ.",
  imageCredit: "ಚಿತ್ರ ಕೃಪೆ",
  explore: "ವರ್ಗಗಳ ಮೂಲಕ ಅನ್ವೇಷಿಸಿ",
  all: "ಎಲ್ಲವೂ",
  shorts: "ಚುಟುಕು ವಿಡಿಯೋಗಳು",
  sort: "ವಿಂಗಡಿಸಿ",
  newest: "ಹೊಸದು ಮೊದಲು",
  oldest: "ಹಳೆಯದು ಮೊದಲು",
  year: "ವರ್ಷ",
  advertisement: "ಜಾಹೀರಾತು",
  adSpace: "ಜಾಹೀರಾತಿಗಾಗಿ ಮೀಸಲಾದ ಸ್ಥಳ",
  password: "ಜ್ವಾಲಾಮಾಲ ಪಾಸ್‌ವರ್ಡ್",
  confirmPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತೆ ನಮೂದಿಸಿ",
  showPassword: "ಪಾಸ್‌ವರ್ಡ್ ತೋರಿಸಿ",
  hidePassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆಮಾಡಿ",
  passwordHint: "ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳ ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ.",
  passwordMismatch: "ಎರಡೂ ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಒಂದೇ ಆಗಿರಬೇಕು.",
  appPasswordHint:
    "ಇಲ್ಲಿ ನಿಮ್ಮ ಜ್ವಾಲಾಮಾಲ ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ. Google ಖಾತೆಗೆ ಮೇಲಿನ Google ಬಟನ್ ಬಳಸಿ.",
  or: "ಅಥವಾ",
  loginMethod: "ಲಾಗಿನ್ ವಿಧಾನ",
  emailLogin: "ಇಮೇಲ್ ಮೂಲಕ ಲಾಗಿನ್",
  phoneLogin: "ಮೊಬೈಲ್ ಒಟಿಪಿ",
  createAccount: "ಹೊಸ ಖಾತೆ ತೆರೆಯಿರಿ",
  forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?",
  sendReset: "ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸಿ",
  backToLogin: "ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
  pleaseWait: "ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ…",
  confirmEmailSent:
    "ಖಾತೆ ಪರಿಶೀಲನೆಗಾಗಿ ನಿಮ್ಮ ಇಮೇಲ್ ನೋಡಿ. ಈಗಾಗಲೇ ಖಾತೆ ಇದ್ದರೆ ಲಾಗಿನ್ ಮಾಡಿ.",
  resetSent:
    "ಈ ಇಮೇಲ್‌ಗೆ ಖಾತೆ ಇದ್ದರೆ ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಕಳುಹಿಸಲಾಗಿದೆ.",
  authRequestFailed:
    "ವಿನಂತಿ ಪೂರ್ಣಗೊಳ್ಳಲಿಲ್ಲ. ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ, ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
  rateLimited:
    "ಇಮೇಲ್/ಒಟಿಪಿ ಕಳುಹಿಸುವ ಮಿತಿ ತಲುಪಿದೆ. ದಯವಿಟ್ಟು ಕೆಲವು ನಿಮಿಷ ಕಾದು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  googleLoginFailed: "Google ಲಾಗಿನ್ ಆರಂಭವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  authLinkFailed:
    "ಲಾಗಿನ್ ಲಿಂಕ್ ಅವಧಿ ಮುಗಿದಿದೆ ಅಥವಾ ಮಾನ್ಯವಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  changePhone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಬದಲಿಸಿ",
  newPassword: "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಿ",
  savePassword: "ಪಾಸ್‌ವರ್ಡ್ ಉಳಿಸಿ",
  passwordUpdated: "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಗಿದೆ. ನಿಮ್ಮ ಖಾತೆಗೆ ಮುಂದುವರಿಯಿರಿ.",
  passwordUpdateFailed:
    "ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಲು ಆಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಹೊಸ ಮರುಹೊಂದಿಸುವ ಲಿಂಕ್ ಪಡೆಯಿರಿ.",
  categoryNews: "ವಿಭಾಗವಾರು ಸುದ್ದಿಗಳು",
  commentsHeading: "ಓದುಗರ ಅಭಿಪ್ರಾಯಗಳು",
  commentsNote:
    "ಎಲ್ಲಾ ಅಭಿಪ್ರಾಯಗಳು ಪರಿಶೀಲನೆಯ ನಂತರ ಕಾಣಿಸುತ್ತವೆ. ಗೌರವಯುತವಾಗಿ ಬರೆಯಿರಿ.",
  commentsLoadFailed:
    "ಅಭಿಪ್ರಾಯಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  yourComment: "ನಿಮ್ಮ ಅಭಿಪ್ರಾಯ",
  sendForReview: "ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಿ",
  commentReceived: "ಪರಿಶೀಲನೆಗಾಗಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ.",
  commentFailed: "ಅಭಿಪ್ರಾಯ ಕಳುಹಿಸಲಾಗಲಿಲ್ಲ.",
  tryLater: "ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
  reportComment: "ವರದಿ ಮಾಡಿ",
  reportSent: "ವರದಿ ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.",
  reportFailed: "ವರದಿ ಕಳುಹಿಸಲಾಗಲಿಲ್ಲ.",
  reason: "ಕಾರಣ",
  send: "ಕಳುಹಿಸಿ",
  connectionError: "ಸಂಪರ್ಕ ದೋಷ.",
  termsAndRefund: "ನಿಯಮಗಳು ಮತ್ತು ಮರುಪಾವತಿ ನೀತಿ",
  agreeToTerms: "ಓದಿ ಒಪ್ಪುತ್ತೇನೆ.",
  oneTime: "ಒಮ್ಮೆ",
  perMonth: "ಪ್ರತಿ ತಿಂಗಳು",
  perYear: "ಪ್ರತಿ ವರ್ಷ",
  billingCyclesNote:
    "ಬಿಲ್ಲಿಂಗ್ ಅವಧಿಗಳವರೆಗೆ ಸ್ವಯಂಚಾಲಿತ ಪಾವತಿ. ಖಾತೆಯಿಂದ ಮುಂದಿನ ಪಾವತಿಗಳನ್ನು ರದ್ದುಪಡಿಸಬಹುದು.",
  supportNow: "ಬೆಂಬಲ ನೀಡಿ",
  paymentConfirmed: "ಪಾವತಿ ದೃಢಪಟ್ಟಿದೆ. ನಿಮ್ಮ ಬೆಂಬಲಕ್ಕೆ ಧನ್ಯವಾದಗಳು.",
  paymentPending:
    "ಪಾವತಿ ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ. ದೃಢಪಟ್ಟ ಪಾವತಿ ನಿಮ್ಮ ಖಾತೆಯಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
  paymentVerifyPending:
    "ಪಾವತಿ ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ. ಮತ್ತೆ ಪಾವತಿಸದೆ ನಿಮ್ಮ ಖಾತೆ ಪರಿಶೀಲಿಸಿ.",
  paymentFailed: "ಪಾವತಿ ಪೂರ್ಣಗೊಳ್ಳಲಿಲ್ಲ. ನಿಮ್ಮ ಖಾತೆಯ ಸ್ಥಿತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.",
  paymentStartFailed:
    "ಪಾವತಿ ಆರಂಭಿಸಲಾಗಲಿಲ್ಲ. ಈಗಾಗಲೇ ಸದಸ್ಯತ್ವವಿದ್ದರೆ ಖಾತೆಯಲ್ಲಿ ಪರಿಶೀಲಿಸಿ.",
  paymentServiceUnavailable: "ಪಾವತಿ ಸೇವೆ ಲಭ್ಯವಿಲ್ಲ.",
  notificationTopics: "ವಿಷಯಗಳು",
  notificationsAllDevices: "ಎಲ್ಲಾ ಸಾಧನಗಳಲ್ಲಿ ಅಧಿಸೂಚನೆಗಳು",
  dailyMax: "ದಿನಕ್ಕೆ ಗರಿಷ್ಠ",
  quietStart: "ಶಾಂತ ಸಮಯ ಆರಂಭ (IST)",
  quietEnd: "ಶಾಂತ ಸಮಯ ಅಂತ್ಯ (IST)",
  breakingOverride: "ಬ್ರೇಕಿಂಗ್ ಸುದ್ದಿಗೆ ಶಾಂತ ಸಮಯದಲ್ಲೂ ಅನುಮತಿ",
  stopOnDevice: "ಈ ಸಾಧನದಲ್ಲಿ ನಿಲ್ಲಿಸಿ",
  pushStoppedDevice: "ಈ ಸಾಧನದ ಅಧಿಸೂಚನೆಗಳು ನಿಲ್ಲಿಸಲಾಗಿದೆ.",
  state: "ರಾಜ್ಯ",
  district: "ಜಿಲ್ಲೆ",
  cityOrTown: "ನಗರ / ಊರು",
  karnataka: "ಕರ್ನಾಟಕ",
  selectStateFirst: "ಮೊದಲು ರಾಜ್ಯ ಆಯ್ಕೆಮಾಡಿ",
  selectDistrictFirst: "ಮೊದಲು ಜಿಲ್ಲೆ ಆಯ್ಕೆಮಾಡಿ",
  noCities: "ನಗರಗಳನ್ನು ಇನ್ನೂ ಸೇರಿಸಿಲ್ಲ",
  membership: "ಸದಸ್ಯತ್ವ",
  cancelSupportNote:
    "ಮುಂದಿನ ಸ್ವಯಂಚಾಲಿತ ಪಾವತಿಗಳನ್ನು ರದ್ದುಪಡಿಸಬಹುದು. ಈಗಾಗಲೇ ಪಾವತಿಸಿದ ಅವಧಿಯ ಸೌಲಭ್ಯಗಳು ಮುಂದುವರಿಯುತ್ತವೆ.",
  cancelRenewal: "ನವೀಕರಣ ರದ್ದುಪಡಿಸಿ",
  confirmStopPayments: "ಹೌದು, ಮುಂದಿನ ಪಾವತಿಗಳನ್ನು ನಿಲ್ಲಿಸಿ",
  renewalCancelled: "ಮುಂದಿನ ಪಾವತಿಗಳನ್ನು ರದ್ದುಪಡಿಸಲಾಗಿದೆ.",
  cancelFailed: "ರದ್ದುಪಡಿಸಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಸಂಪರ್ಕಿಸಿ.",
  sponsorApproved:
    "ಅನುಮೋದಿಸಲಾಗಿದೆ. ಅಂತಿಮ ಪ್ರಕಟಣೆಯನ್ನು ಸಂಪಾದಕರು ನಿರ್ಧರಿಸುತ್ತಾರೆ.",
  sponsorApprovalIntro:
    "ಈ ಆವೃತ್ತಿಯನ್ನು ಪ್ರಾಯೋಜಕರ ಪರವಾಗಿ ಪರಿಶೀಲಿಸಿ ಅನುಮೋದಿಸುತ್ತಿದ್ದೀರಿ.",
  approveVersion: "ಈ ಆವೃತ್ತಿಗೆ ಅನುಮೋದನೆ ನೀಡಿ",
  sponsorLinkExpired:
    "ಆವೃತ್ತಿ ಬದಲಾಗಿದೆ ಅಥವಾ ಲಿಂಕ್ ಅವಧಿ ಮುಗಿದಿದೆ. ಹೊಸ ಲಿಂಕ್ ಪಡೆಯಿರಿ.",
  openVideo: "ವೀಡಿಯೊ ತೆರೆಯಿರಿ",
  resumeAt: "ಮುಂದುವರಿಸಿ",
  startOver: "ಆರಂಭದಿಂದ",
  videoChapters: "ವೀಡಿಯೊ ಅಧ್ಯಾಯಗಳು",
  cancelReminder: "ಜ್ಞಾಪನೆ ರದ್ದುಮಾಡಿ",
  notificationSettings: "ಅಧಿಸೂಚನೆಗಳ ಸೆಟ್ಟಿಂಗ್",
  continueWatching: "ವೀಕ್ಷಣೆ ಮುಂದುವರಿಸಿ",
  featuredPhoto: "ವಿಶೇಷ ಚಿತ್ರ",
  onThisDay: "ಇತಿಹಾಸದಲ್ಲಿ ಈ ದಿನ",
  loadingContent: "ವಿಷಯ ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
  closeAd: "ಜಾಹೀರಾತು ಮುಚ್ಚಿ",
  totalChoices: "ಒಟ್ಟು ಆಯ್ಕೆಗಳು",
  preferredSourceNote:
    "Google ನಲ್ಲಿ ಜ್ವಾಲಾಮಾಲ ಸುದ್ದಿಗಳನ್ನು ಆದ್ಯತೆಯಾಗಿ ಆಯ್ಕೆಮಾಡಿ.",
  condolenceMessages: "ಸಂತಾಪ ಸಂದೇಶಗಳು",
  messagesAfterReview: "ಸಂದೇಶಗಳು ಪರಿಶೀಲನೆಯ ನಂತರ ಪ್ರಕಟವಾಗುತ್ತವೆ.",
  readInKannada: "ಕನ್ನಡದಲ್ಲಿ ಓದಿ",
  readInEnglish: "Read in English",
  readInHindi: "हिंदी में पढ़ें",
  machineTranslated: "ಕನ್ನಡದಿಂದ ಯಂತ್ರ ಅನುವಾದ, ಇನ್ನೂ ಪರಿಶೀಲಿಸಿಲ್ಲ",
  sponsoredContent: "ಪ್ರಾಯೋಜಿತ ವಿಷಯ",
  contributorApplication: "ನಾಗರಿಕ ವರದಿಗಾರರ ಅರ್ಜಿ",
  contributorIntro:
    "ಪರಿಶೀಲಿಸಿದ ಮೊಬೈಲ್ ಒಟಿಪಿ ಮೂಲಕ ಲಾಗಿನ್ ಮಾಡಿ, ನಂತರ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ. ನಿರ್ವಾಹಕರು ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ಪರಿಶೀಲಿಸಿ ವರದಿ ಮಾಡುವ ಪ್ರದೇಶವನ್ನು ನಿಗದಿಪಡಿಸುತ್ತಾರೆ. ನಿಮ್ಮ ಬರಹಗಳು ಸಂಪಾದಕೀಯ ಪರಿಶೀಲನೆಗಾಗಿ ಕರಡು ಆಗಿ ಉಳಿಯುತ್ತವೆ.",
  reportingArea: "ವರದಿ ಮಾಡುವ ಪ್ರದೇಶ",
  yourExperience: "ನಿಮ್ಮ ಅನುಭವ",
  applyNow: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
  applicationSent: "ಅರ್ಜಿ ಪರಿಶೀಲನೆಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.",
  submitFailed: "ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
  contributorDetailsNeeded:
    "ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ವರದಿಗಾರಿಕೆಯ ಅನುಭವವನ್ನು ವಿವರಿಸಿ.",
  contributorPhoneNeeded:
    "ಫೋನ್ OTP ಪರಿಶೀಲನೆ ಅಗತ್ಯ. ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೊಮ್ಮೆ ಪ್ರಯತ್ನಿಸಿ.",
  earlyAccess: "ಬೆಂಬಲಿಗರಿಗೆ ಮುಂಗಡ ಪ್ರವೇಶ",
  noEarlyAccess: "ನಿಮ್ಮ ಖಾತೆಗೆ ಲಭ್ಯವಿರುವ ಮುಂಗಡ ಸುದ್ದಿಗಳಿಲ್ಲ.",
  supportBrand: "{brand}ಗೆ ಬೆಂಬಲ ನೀಡಿ",
  supportIntro: "ನಮ್ಮ ಸಮುದಾಯದ ಸುದ್ದಿಸೇವೆಗೆ ನಿಮ್ಮ ಬೆಂಬಲ.",
  payee: "ಪಾವತಿ ಸ್ವೀಕರಿಸುವವರು",
  mySupportAndPayments: "ನನ್ನ ಬೆಂಬಲ ಮತ್ತು ಪಾವತಿಗಳು",
  supportPaymentsNotLive:
    "ಆನ್‌ಲೈನ್ ಬೆಂಬಲ ಪಾವತಿಗಳು ಇನ್ನೂ ಆರಂಭವಾಗಿಲ್ಲ. ವಿವರಗಳಿಗೆ",
  contactUs: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
  supportTerms: "ಬೆಂಬಲದ ನಿಯಮಗಳು",
  refundPolicy: "ಮರುಪಾವತಿ ನೀತಿ",
  contactLabel: "ಸಂಪರ್ಕ",
  supportTermsPending:
    "ಪಾವತಿ ಸೇವೆ ಆರಂಭಿಸುವ ಮೊದಲು ನಿಯಮಗಳನ್ನು ಇಲ್ಲಿ ಪ್ರಕಟಿಸಲಾಗುತ್ತದೆ.",
  mySupport: "ನನ್ನ ಬೆಂಬಲ",
  supporterActiveUntil: "ಬೆಂಬಲಿಗ · {date} ವರೆಗೆ ಸಕ್ರಿಯ",
  paymentHistory: "ಪಾವತಿ ಇತಿಹಾಸ",
  date: "ದಿನಾಂಕ",
  amount: "ಮೊತ್ತ",
  paymentId: "ಪಾವತಿ ಸಂಖ್ಯೆ",
  paymentCaptured: "ದೃಢಪಟ್ಟಿದೆ",
  refunded: "ಮರುಪಾವತಿ",
  noPayments: "ದೃಢಪಟ್ಟ ಪಾವತಿಗಳಿಲ್ಲ.",
  citizenReporter: "ನಾಗರಿಕ ವರದಿಗಾರ",
  earlyAccessShort: "ಮುಂಗಡ ಪ್ರವೇಶ",
  fullScreenStory: "ಪೂರ್ಣ ಪರದೆಯ ಚಿತ್ರಕಥೆ",
  newsNearYou: "ನಿಮ್ಮ ಪ್ರದೇಶದ ಸುದ್ದಿ",
  editorPicks: "ಸಂಪಾದಕರ ಆಯ್ಕೆ",
  pages: "ಪುಟಗಳು",
  siteLanguage: "ತಾಣದ ಭಾಷೆ",
} as const;
export const months = [
  "ಜನವರಿ",
  "ಫೆಬ್ರವರಿ",
  "ಮಾರ್ಚ್",
  "ಏಪ್ರಿಲ್",
  "ಮೇ",
  "ಜೂನ್",
  "ಜುಲೈ",
  "ಆಗಸ್ಟ್",
  "ಸೆಪ್ಟೆಂಬರ್",
  "ಅಕ್ಟೋಬರ್",
  "ನವೆಂಬರ್",
  "ಡಿಸೆಂಬರ್",
];
export const weekdays = ["ಭಾನು", "ಸೋಮ", "ಮಂಗಳ", "ಬುಧ", "ಗುರು", "ಶುಕ್ರ", "ಶನಿ"];

export const v4 = {
  correctionsIntro:
    "ಪ್ರಕಟಿತ ವರದಿಗಳ ಪ್ರಮುಖ ತಿದ್ದುಪಡಿಗಳು ಮತ್ತು ಸ್ಪಷ್ಟೀಕರಣಗಳನ್ನು ಇಲ್ಲಿ ದಾಖಲಿಸಲಾಗುತ್ತದೆ. ವರದಿಯಲ್ಲಿ ದೋಷ ಕಂಡರೆ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ.",
  noCorrections: "ತಿದ್ದುಪಡಿ ದಾಖಲೆಗಳು ಇನ್ನೂ ಪ್ರಕಟವಾಗಿಲ್ಲ.",
  editorialPolicy: "ಸಂಪಾದಕೀಯ ನೀತಿ",
  factCheckPolicy: "ಸತ್ಯ ಪರಿಶೀಲನೆ ನೀತಿ",
  theme: "ನೋಟ",
  systemTheme: "ಸಾಧನದ ನೋಟ",
  captionTooLong: "ಸಂದೇಶ ಬಹಳ ಉದ್ದವಾಗಿದೆ. ಕಡಿಮೆ ವರದಿಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿ.",
  distributionReview:
    "ಆಯ್ದ ಪ್ರಕಟಿತ ವರದಿಗಳಿಂದ ಕರಡು ರಚಿಸಿ. ಪೂರ್ಣ ಸಂದೇಶವನ್ನು ಪರಿಶೀಲಿಸಿ ಕಳುಹಿಸಲು ಅನುಮೋದಿಸಿ.",
  network: "ಜಾಲತಾಣ",
  createDraft: "ಕರಡು ರಚಿಸಿ",
  queued: "ಕಳುಹಿಸುವ ಸರದಿಗೆ ಸೇರಿಸಲಾಗಿದೆ.",
  approveAndQueue: "ಪರಿಶೀಲಿಸಿ ಕಳುಹಿಸಲು ಅನುಮೋದಿಸಿ",
  channelId: "ಪುಟ / ಚಾನೆಲ್ ID",
  accessToken: "ಸೇವೆಯ ಪ್ರವೇಶ ಟೋಕನ್",
  activeSubscribers: "ದೃಢೀಕೃತ ಚಂದಾದಾರರು",
  jobs: "ಹಿನ್ನೆಲೆ ಕಾರ್ಯಗಳು",
  status: "ಸ್ಥಿತಿ",
  attempts: "ಪ್ರಯತ್ನಗಳು",
  audioPlayFailed:
    "ಧ್ವನಿ ಆರಂಭಿಸಲಾಗಲಿಲ್ಲ. ಪ್ಲೇ ಬಟನ್ ಒತ್ತಿ ಅಥವಾ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
  audioProgress: "ಧ್ವನಿ ಪ್ರಗತಿ",
  audioSpeed: "ಕೇಳುವ ವೇಗ",
  liveReaders: "ಈಗ ಓದುತ್ತಿರುವವರು",
  analyticsWindow:
    "ಕಳೆದ 5 ನಿಮಿಷಗಳಲ್ಲಿ ಕಂಡ ಅನಾಮಧೇಯ ಅವಧಿಗಳು. ಮಾದರಿ ವಿಷಯದ ಚಟುವಟಿಕೆ ಲೆಕ್ಕಕ್ಕೆ ಬರುವುದಿಲ್ಲ.",
  views: "ಓದುವಿಕೆಗಳು",
  engagedSeconds: "ಸಕ್ರಿಯ ಓದುವ ಸೆಕೆಂಡುಗಳು",
  shares: "ಹಂಚಿಕೆಗಳು",
  listens: "ಕೇಳುವಿಕೆಗಳು",
  refresh: "ನವೀಕರಿಸಿ",
  title: "ಶೀರ್ಷಿಕೆ",
  campaigns: "ಜಾಹೀರಾತು ಅಭಿಯಾನಗಳು",
  legacySlot: "ಮೂಲ ಜಾಹೀರಾತು ಸ್ಥಾನ",
  image: "ಚಿತ್ರದ ಕೊಂಡಿ",
  mobileImage: "ಮೊಬೈಲ್ ಚಿತ್ರದ ಕೊಂಡಿ",
  alt: "ಚಿತ್ರ ವಿವರಣೆ",
  adSlots: "ಜಾಹೀರಾತು ಸ್ಥಾನಗಳು",
  targetPages: "ಪುಟ ವಿಧಗಳು — ಸಾಲಿಗೊಂದು",
  device: "ಸಾಧನ",
  weight: "ಪ್ರದರ್ಶನ ತೂಕ",
  impressionCap: "ಒಟ್ಟು ಪ್ರದರ್ಶನ ಮಿತಿ",
  clickCap: "ಒಟ್ಟು ಕ್ಲಿಕ್ ಮಿತಿ",
  dailyCap: "ದಿನದ ಪ್ರದರ್ಶನ ಮಿತಿ",
  sponsored: "ಪ್ರಾಯೋಜಿತ",
  adCspReady: "ಜಾಹೀರಾತು ಸುರಕ್ಷತಾ ಸಂರಚನೆ ಸಿದ್ಧವಾಗಿದೆ.",
  adCspMissing:
    "ನೈಜ Google ಜಾಹೀರಾತಿಗೆ ಸರ್ವರ್‌ನಲ್ಲಿ ADS_STRICT_CSP=true ಹೊಂದಿಸಬೇಕು.",
  format: "ವಿನ್ಯಾಸ",
  creatives: "ಜಾಹೀರಾತು ಚಿತ್ರಗಳು",
  adReport: "ಜಾಹೀರಾತು ವರದಿ",
  impressions: "ಪ್ರದರ್ಶನಗಳು",
  clicks: "ಕ್ಲಿಕ್‌ಗಳು",
  deskHint:
    "ವರದಿಗಳನ್ನು ಹಂತವಾರು ನಿರ್ವಹಿಸಿ. ಈ ಫಲಕದ ಹಂತ ಬದಲಾವಣೆ ವರದಿಯನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪ್ರಕಟಿಸುವುದಿಲ್ಲ.",
  unassigned: "ನಿಯೋಜಿಸಿಲ್ಲ",
  assignee: "ವರದಿಗಾರರು",
  priority: "ಆದ್ಯತೆ",
  paragraph: "ಪ್ಯಾರಾಗ್ರಾಫ್ ಕ್ರಮಾಂಕ (ಮೊದಲದು 0)",
  checkInbox: "ನಿಮ್ಮ ಇಮೇಲ್‌ನಲ್ಲಿರುವ ದೃಢೀಕರಣ ಕೊಂಡಿ ಪರಿಶೀಲಿಸಿ.",
  newsletterHint:
    "ನಿಮ್ಮ ಆಯ್ಕೆಯ ಸುದ್ದಿ ಸಂಚಿಕೆ ಇಮೇಲ್‌ನಲ್ಲಿ ಪಡೆಯಿರಿ. ದೃಢೀಕರಣದ ನಂತರ ಮಾತ್ರ ಚಂದಾದಾರಿಕೆ ಆರಂಭವಾಗುತ್ತದೆ. ಯಾವಾಗ ಬೇಕಾದರೂ ನಿಲ್ಲಿಸಬಹುದು.",
  frequency: "ಸಂಚಿಕೆಯ ಅವಧಿ",
  weekly: "ವಾರಕ್ಕೊಮ್ಮೆ",
  daily: "ಪ್ರತಿದಿನ",
  confirmNewsletter: "ಇಮೇಲ್ ಚಂದಾದಾರಿಕೆ ದೃಢೀಕರಿಸಿ",
  subscriptionConfirmed: "ಚಂದಾದಾರಿಕೆ ದೃಢೀಕರಿಸಲಾಗಿದೆ.",
  unsubscribed: "ಚಂದಾದಾರಿಕೆ ನಿಲ್ಲಿಸಲಾಗಿದೆ.",
  linkExpired: "ಈ ಕೊಂಡಿ ಅವಧಿ ಮುಗಿದಿದೆ ಅಥವಾ ಈಗಾಗಲೇ ಬಳಸಲಾಗಿದೆ.",
  providerDisabled: "ಸೇವೆ ನಿಷ್ಕ್ರಿಯವಾಗಿದೆ ಅಥವಾ ಬಳಕೆಯ ಮಿತಿ ತಲುಪಿದೆ.",
  aiSensitive: "ಈ ವರ್ಗದಲ್ಲಿ AI ಸಲಹೆಗಳನ್ನು ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಲಾಗಿದೆ.",
  aiSuggestion: "AI ಸಲಹೆ",
  aiReview:
    "ಸಲಹೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ. ಆಯ್ದ ಸಲಹೆಯನ್ನು ಬಳಸಿದ ನಂತರ ವರದಿಯನ್ನು ಪ್ರತ್ಯೇಕವಾಗಿ ಉಳಿಸಿ.",
  generate: "ಸಲಹೆ ರಚಿಸಿ",
  accepted: "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
  budgetNote:
    "ಮಾಸಿಕ ಮಿತಿಗಳು ಸೇವೆಯ ವೆಚ್ಚವನ್ನು ನಿಯಂತ್ರಿಸುತ್ತವೆ. AI ಬಳಕೆಯಲ್ಲಿ ಗರಿಷ್ಠ ಅಂದಾಜು ಮುಂಗಡ ಕಾಯ್ದಿರಿಸಲಾಗುತ್ತದೆ.",
  credentialsReady: "ಸೇವೆಯ ಕೀಗಳನ್ನು ಹೊಂದಿಸಲಾಗಿದೆ",
  credentialsMissing: "ಸೇವೆಯ ಕೀಗಳು ಇನ್ನೂ ಬೇಕು",
  usage: "ಈ ತಿಂಗಳ ಬಳಕೆ",
  monthlyLimit: "ಮಾಸಿಕ ಬಳಕೆ ಮಿತಿ",
  aiBlockedCategories: "AI ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿದ ವರ್ಗಗಳು",
  role: "ಪಾತ್ರ",
  roles: "ಪಾತ್ರಗಳು ಮತ್ತು ಅನುಮತಿಗಳು",
  embargo: "ಪ್ರಕಟಣೆ ತಡೆ ಸಮಯ (IST)",
  quickSummary: "ಸಂಕ್ಷಿಪ್ತ ಮುಖ್ಯಾಂಶಗಳು — ಸಾಲಿಗೊಂದು",
  hideAds: "ಈ ಲೇಖನದಲ್ಲಿ ಜಾಹೀರಾತು ಮರೆಮಾಡಿ",
  meaningfulEdit: "ಓದುಗರಿಗೆ ತಿಳಿಸಬೇಕಾದ ಪ್ರಮುಖ ತಿದ್ದುಪಡಿ",
  locked: "ಇನ್ನೊಬ್ಬ ಸಂಪಾದಕರು ಈ ವರದಿ ತಿದ್ದುತ್ತಿದ್ದಾರೆ.",
  restore: "ಕರಡು ಆಗಿ ಮರುಸ್ಥಾಪಿಸಿ",
  reviewNote: "ಪರಿಶೀಲನಾ ಟಿಪ್ಪಣಿ",
  publishChecklist:
    "ಪ್ರಕಟಣೆಗೆ ಮುನ್ನ: ದಿನಾಂಕ, ವರ್ಗ, ಸಾರಾಂಶ, ಚಿತ್ರ ಕೃಪೆ ಮತ್ತು 110 ಅಕ್ಷರದೊಳಗಿನ ಶೀರ್ಷಿಕೆ ಪರಿಶೀಲಿಸಿ.",
  samplePoll: "ಮಾದರಿ ಮತಗಟ್ಟೆ — ನಿಮ್ಮ ಆಯ್ಕೆ ಪರೀಕ್ಷೆಗಾಗಿ ಮಾತ್ರ.",
  localOnly: "ಈ ಸಾಧನದಲ್ಲಿ ಮಾತ್ರ ದಾಖಲಿಸಲಾಗಿದೆ.",
  voteFailed:
    "ಮತವನ್ನು ದಾಖಲಿಸಲಾಗಲಿಲ್ಲ. ಮತದಾನ ಮುಗಿದಿರಬಹುದು ಅಥವಾ ನೀವು ಈಗಾಗಲೇ ಮತ ನೀಡಿರಬಹುದು.",
  totalVotes: "ಒಟ್ಟು ಮತಗಳು",
  showScore: "ಫಲಿತಾಂಶ ನೋಡಿ",
  tryAgain: "ಮತ್ತೊಮ್ಮೆ ಪ್ರಯತ್ನಿಸಿ",
  questions: "ಪ್ರಶ್ನೆಗಳು",
  reactions: "ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ",
  namana: "ನಮನ",
  useful: "ಉಪಯುಕ್ತ",
  sad: "ದುಃಖ",
  thankYou: "ಧನ್ಯವಾದಗಳು",
  waterLevel: "ನೀರಿನ ಮಟ್ಟ",
  recentReadings: "ಇತ್ತೀಚಿನ ದಾಖಲೆಗಳು",
  noVerifiedData: "ಪರಿಶೀಲಿಸಿದ ಮಾಹಿತಿ ಇನ್ನೂ ಲಭ್ಯವಿಲ್ಲ.",
  rateDisclaimer:
    "ದರಗಳು ಪ್ರಕಟಿತ ಮೂಲ ಮತ್ತು ದಿನಾಂಕಕ್ಕೆ ಸಂಬಂಧಿಸಿದವು. ಸ್ಥಳೀಯ ಮಾರಾಟದ ದರ ವ್ಯತ್ಯಾಸವಾಗಬಹುದು.",
  price: "ದರ",
  organization: "ಸಂಸ್ಥೆ",
  feed: "ನಿಮ್ಮ ಸುದ್ದಿ",
  syncFailed: "ಖಾತೆಯೊಂದಿಗೆ ಮಾಹಿತಿ ಹೊಂದಾಣಿಕೆ ಆಗಲಿಲ್ಲ. ಸ್ಥಳೀಯ ಮಾಹಿತಿ ಉಳಿಸಲಾಗಿದೆ.",
  edit: "ತಿದ್ದುಪಡಿ",
  select: "ಆಯ್ಕೆ ಮಾಡಿ",
  answerNumberHint: "ಸರಿಯಾದ ಉತ್ತರದ ಕ್ರಮಾಂಕ: ಮೊದಲ ಆಯ್ಕೆ 0, ಎರಡನೇ ಆಯ್ಕೆ 1.",
  latitude: "ಅಕ್ಷಾಂಶ",
  longitude: "ರೇಖಾಂಶ",
  credentials: "ಅರ್ಹತೆ ಮತ್ತು ಅನುಭವ",
  deity: "ಆರಾಧ್ಯ ದೇವರು",
  options: "ಆಯ್ಕೆಗಳು",
  fullLevel: "ಗರಿಷ್ಠ ಮಟ್ಟ (m)",
  currentLevel: "ಇಂದಿನ ಮಟ್ಟ (m)",
  inflow: "ಒಳಹರಿವು (cusecs)",
  outflow: "ಹೊರಹರಿವು (cusecs)",
  value: "ಮೌಲ್ಯ",
  unit: "ಘಟಕ",
  addRow: "ಸಾಲು ಸೇರಿಸಿ",
  remove: "ತೆಗೆದುಹಾಕಿ",
  caption: "ಚಿತ್ರದ ವಿವರಣೆ",
  note: "ಟಿಪ್ಪಣಿ",
  question: "ಪ್ರಶ್ನೆ",
  answer: "ಸರಿಯಾದ ಉತ್ತರ",
  explanation: "ವಿವರಣೆ",
  nearMe: "ನನ್ನ ಹತ್ತಿರ",
  savedPlace: "ಉಳಿಸಿದ ಊರು",
  locationFailed: "ಸ್ಥಳವನ್ನು ತಿಳಿಯಲು ಆಗಲಿಲ್ಲ. ಪಟ್ಟಿಯಿಂದ ಊರನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
  rain: "ಮಳೆಯ ಸಾಧ್ಯತೆ",
  weatherAvailability:
    "ಪರಿಶೀಲಿಸಿದ ಹವಾಮಾನ ಮಾಹಿತಿ ಲಭ್ಯವಾದಾಗ ಇಲ್ಲಿ ಪ್ರಕಟವಾಗುತ್ತದೆ.",
  aqiNote:
    "ಇದು ಮಾದರಿ ಆಧಾರಿತ ಅಂದಾಜು; ಅಧಿಕೃತ ನಿಲ್ದಾಣದ ಮಾಪನವಲ್ಲ. ಸೂಚ್ಯಂಕಕ್ಕೆ ಲಭ್ಯವಿರುವ 24 ಗಂಟೆಯ PM2.5, PM10, NO₂ ಮತ್ತು SO₂ ಸರಾಸರಿಗಳನ್ನು ಬಳಸಲಾಗುತ್ತದೆ.",
  contentType: "ವಿಷಯದ ವಿಧ",
  trendingTopics: "ಈಗ ಚರ್ಚೆಯಲ್ಲಿ",
  topics: "ವಿಷಯ ಸಂಗ್ರಹ",
  tags: "ಟ್ಯಾಗ್‌ಗಳು",
  popularTags: "ಜನಪ್ರಿಯ ಟ್ಯಾಗ್‌ಗಳು",
  places: "ಊರುಗಳು",
  authors: "ಲೇಖಕರು",
  series: "ವಿಡಿಯೋ ಸರಣಿಗಳು",
  episodes: "ಸಂಚಿಕೆಗಳು",
  keyFacts: "ಮುಖ್ಯ ಮಾಹಿತಿ",
  timeline: "ಘಟನೆಗಳ ಹಾದಿ",
  pinned: "ಆಯ್ದ ವರದಿಗಳು",
  archive: "ಸುದ್ದಿ ಸಂಗ್ರಹ",
  allTopics: "ಎಲ್ಲಾ ವಿಷಯಗಳು",
  weather: "ಹವಾಮಾನ",
  jainCalendar: "ಜೈನ ಪಂಚಾಂಗ",
  dailyTimes: "ಇಂದಿನ ಸಮಯ",
  sunrise: "ಸೂರ್ಯೋದಯ",
  sunset: "ಸೂರ್ಯಾಸ್ತ",
  timeNote: "ಸಮಯಗಳು ಅಂದಾಜು; ಸ್ಥಳೀಯ ಪಂಚಾಂಗ ನೋಡಿ",
  observancePending:
    "ಧಾರ್ಮಿಕ ಆಚರಣೆಗಳ ಸಮಯವನ್ನು ಸಮುದಾಯದ ಸಲಹೆಗಾರರ ಪರಿಶೀಲನೆಯ ನಂತರ ಸೇರಿಸಲಾಗುತ್ತದೆ.",
  choosePlace: "ಊರು ಆಯ್ಕೆಮಾಡಿ",
  changePlace: "ಊರು ಬದಲಿಸಿ",
  updated: "ನವೀಕರಿಸಲಾಗಿದೆ",
  source: "ಮೂಲ",
  stale: "ಹಳೆಯ ಮಾಹಿತಿ",
  noWeather: "ಈ ಊರಿನ ಹವಾಮಾನ ಮಾಹಿತಿ ಸದ್ಯ ಲಭ್ಯವಿಲ್ಲ.",
  forecast: "ಮುಂದಿನ ದಿನಗಳ ಮುನ್ಸೂಚನೆ",
  hourly: "ಗಂಟೆಗೊಮ್ಮೆ",
  temperature: "ತಾಪಮಾನ",
  humidity: "ತೇವಾಂಶ",
  wind: "ಗಾಳಿ",
  feelsLike: "ಅನುಭವದ ತಾಪಮಾನ",
  airQuality: "ಗಾಳಿಯ ಗುಣಮಟ್ಟ",
  estimated: "ಅಂದಾಜು",
  dataUnavailable: "ಮಾಹಿತಿ ಇನ್ನೂ ಲಭ್ಯವಿಲ್ಲ",
  noCalendar: "ಈ ತಿಂಗಳಿಗೆ ಪರಿಶೀಲಿಸಿದ ಪಂಚಾಂಗ ಮಾಹಿತಿ ಇನ್ನೂ ಸೇರಿಸಿಲ್ಲ.",
  basadis: "ಬಸದಿಗಳ ಪರಿಚಯ",
  notices: "ಸಮುದಾಯ ಪ್ರಕಟಣೆ",
  opportunities: "ಅವಕಾಶಗಳು",
  district: "ಜಿಲ್ಲೆ",
  timings: "ದರ್ಶನ ಸಮಯ",
  map: "ನಕ್ಷೆ ತೆರೆಯಿರಿ",
  relatedNews: "ಸಂಬಂಧಿತ ಸುದ್ದಿಗಳು",
  obituary: "ಶ್ರದ್ಧಾಂಜಲಿ",
  submitNotice: "ಪ್ರಕಟಣೆ ಕಳುಹಿಸಿ",
  submitOpportunity: "ಅವಕಾಶದ ಮಾಹಿತಿ ಕಳುಹಿಸಿ",
  deadline: "ಕೊನೆಯ ದಿನಾಂಕ",
  organisation: "ಸಂಸ್ಥೆ",
  apply: "ವಿವರಗಳನ್ನು ನೋಡಿ",
  job: "ಉದ್ಯೋಗ",
  scholarship: "ವಿದ್ಯಾರ್ಥಿವೇತನ",
  competition: "ಸ್ಪರ್ಧೆ",
  admission: "ಪ್ರವೇಶಾತಿ",
  gallery: "ಚಿತ್ರ ಸಂಗ್ರಹ",
  stories: "ಚಿತ್ರಕಥೆಗಳು",
  liveblogs: "ನೇರ ವರದಿಗಳು",
  liveblog: "ನೇರ ವರದಿ",
  newUpdates: "ಹೊಸ ಅಪ್‌ಡೇಟ್‌ಗಳು",
  loadUpdates: "ಹೊಸ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ತೋರಿಸಿ",
  ended: "ನೇರ ವರದಿ ಮುಗಿದಿದೆ",
  polls: "ನಿಮ್ಮ ಅಭಿಪ್ರಾಯ",
  vote: "ಮತ ನೀಡಿ",
  pollClosed: "ಮತದಾನ ಮುಗಿದಿದೆ",
  pollSaved: "ನಿಮ್ಮ ಮತ ದಾಖಲಾಗಿದೆ",
  sampleVote: "ಇದು ಮಾದರಿ ಮತದಾನ. ಫಲಿತಾಂಶ ಈ ಸಾಧನಕ್ಕೆ ಮಾತ್ರ.",
  quizzes: "ರಸಪ್ರಶ್ನೆಗಳು",
  checkAnswer: "ಉತ್ತರ ಪರಿಶೀಲಿಸಿ",
  score: "ಅಂಕಗಳು",
  restart: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
  reservoirs: "ಜಲಾಶಯಗಳ ನೀರಿನ ಮಟ್ಟ",
  rates: "ಇಂದಿನ ದರಗಳು",
  storage: "ಸಂಗ್ರಹ",
  rateGold22: "ಚಿನ್ನ 22K",
  rateGold24: "ಚಿನ್ನ 24K",
  rateSilver: "ಬೆಳ್ಳಿ",
  ratePetrol: "ಪೆಟ್ರೋಲ್",
  rateDiesel: "ಡೀಸೆಲ್",
  readingTools: "ಓದುವ ಆಯ್ಕೆಗಳು",
  textSize: "ಅಕ್ಷರದ ಗಾತ್ರ",
  lineSpace: "ಸಾಲಿನ ಅಂತರ",
  contrast: "ಹೆಚ್ಚಿನ ಕಾಂಟ್ರಾಸ್ಟ್",
  print: "ಮುದ್ರಿಸಿ",
  listen: "ಈ ಸುದ್ದಿ ಕೇಳಿ",
  pause: "ವಿರಾಮ",
  resume: "ಮುಂದುವರಿಸಿ",
  stop: "ನಿಲ್ಲಿಸಿ",
  readingTime: "ಓದುವ ಸಮಯ",
  minutes: "ನಿಮಿಷ",
  follow: "ಅನುಸರಿಸಿ",
  following: "ಅನುಸರಿಸಲಾಗುತ್ತಿದೆ",
  localFollow: "ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲಾಗಿದೆ. ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿದಾಗ ಹೊಂದಿಸಲಾಗುತ್ತದೆ.",
  myFeed: "ನಿಮಗಾಗಿ",
  history: "ಓದಿದ ಸುದ್ದಿಗಳು",
  clearHistory: "ಇತಿಹಾಸ ತೆರವುಗೊಳಿಸಿ",
  newsletter: "ಸುದ್ದಿ ಸಂಚಿಕೆ",
  subscribe: "ಚಂದಾದಾರರಾಗಿ",
  unsubscribe: "ಚಂದಾದಾರಿಕೆ ರದ್ದುಮಾಡಿ",
  newsletterNote: "ಇಮೇಲ್‌ಗೆ ಬಂದ ಲಿಂಕ್ ಮೂಲಕ ಚಂದಾದಾರಿಕೆಯನ್ನು ದೃಢಪಡಿಸಿ.",
  channels: "ನಮ್ಮ ಚಾನಲ್‌ಗಳು",
  editorial: "ಸಂಪಾದಕೀಯ ನೀತಿ",
  corrections: "ತಿದ್ದುಪಡಿಗಳು",
  factcheck: "ಸತ್ಯಶೋಧನೆ ನೀತಿ",
  ownership: "ಮಾಲೀಕತ್ವ ಮತ್ತು ಹಣಕಾಸು",
  trustDraft:
    "ಇದು ನೀತಿಯ ಕರಡು. ಸಂಸ್ಥೆಯ ಪರಿಶೀಲನೆ ಮತ್ತು ಅನುಮೋದನೆಯ ನಂತರ ಅಂತಿಮ ನೀತಿ ಪ್ರಕಟವಾಗಲಿದೆ.",
  credit: "ಚಿತ್ರ",
  nextEpisode: "ಮುಂದಿನ ಸಂಚಿಕೆ",
  previousStory: "ಹಿಂದಿನ ಸುದ್ದಿ",
  nextStory: "ಮುಂದಿನ ಸುದ್ದಿ",
  desk: "ಸುದ್ದಿ ವಿಭಾಗ",
  review: "ಪರಿಶೀಲನೆ",
  versions: "ಹಿಂದಿನ ಆವೃತ್ತಿಗಳು",
  assistant: "ಸಂಪಾದಕೀಯ ಸಹಾಯಕ",
  analytics: "ಓದುಗರ ಅಂಕಿಅಂಶ",
  social: "ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ",
  providers: "ಸೇವಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  budgets: "ಬಳಕೆಯ ಮಿತಿಗಳು",
  moderation: "ಪ್ರಕಟಣೆಯ ಪರಿಶೀಲನೆ",
  pending: "ಪರಿಶೀಲನೆಗೆ ಬಾಕಿ",
  approved: "ಅನುಮೋದಿಸಲಾಗಿದೆ",
  reject: "ತಿರಸ್ಕರಿಸಿ",
  approve: "ಅನುಮೋದಿಸಿ",
  draft: "ಕರಡು",
  publish: "ಪ್ರಕಟಿಸಿ",
  saveDraft: "ಕರಡು ಉಳಿಸಿ",
  suggestions: "ಸಲಹೆಗಳು",
  accept: "ಸ್ವೀಕರಿಸಿ",
  enabled: "ಸಕ್ರಿಯ",
  disabled: "ನಿಷ್ಕ್ರಿಯ",
  start: "ಆರಂಭ",
  end: "ಅಂತ್ಯ",
  order: "ಕ್ರಮ",
  hide: "ಮರೆಮಾಡಿ",
  merge: "ಒಂದಾಗಿಸಿ",
  newItem: "ಹೊಸ ದಾಖಲೆ",
  saved: "ಉಳಿಸಲಾಗಿದೆ",
  failed: "ವಿನಂತಿ ಪೂರ್ಣಗೊಳ್ಳಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  serviceOff: "ಈ ಸೇವೆ ಇನ್ನೂ ಸಕ್ರಿಯಗೊಂಡಿಲ್ಲ.",
  sample: "ಮಾದರಿ",
  readingHistoryEmpty: "ಓದಿದ ಸುದ್ದಿಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.",
  noFollow: "ನೀವು ಅನುಸರಿಸುವ ವಿಷಯಗಳ ಸುದ್ದಿಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.",
  support: "ಜ್ವಾಲಾಮಾಲಗೆ ಬೆಂಬಲ",
  paymentsUnavailable: "ಬೆಂಬಲ ಸೇವೆಯ ವಿವರಗಳನ್ನು ಶೀಘ್ರದಲ್ಲೇ ಪ್ರಕಟಿಸಲಾಗುತ್ತದೆ.",
  openMenu: "ಎಲ್ಲಾ ವಿಭಾಗಗಳನ್ನು ತೆರೆಯಿರಿ",
  closeMenu: "ವಿಭಾಗಗಳ ಪಟ್ಟಿ ಮುಚ್ಚಿ",
  more: "ಇನ್ನಷ್ಟು",
  liveSample: "ನೇರ ವರದಿಯ ಮಾದರಿ",
  shareWhatsApp: "WhatsApp ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ",
  clear: "ತೆರವುಗೊಳಿಸಿ",
  loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
  shorts: "ಶಾರ್ಟ್ಸ್",
  read: "ಓದಿ",
  homeSections: "ಮುಖಪುಟದ ವಿಭಾಗಗಳು",
  adManager: "ಜಾಹೀರಾತು ನಿರ್ವಹಣೆ",
  import: "ವಿಡಿಯೋ ಆಮದು",
  report: "ವರದಿ",
  exportCsv: "CSV ಡೌನ್‌ಲೋಡ್",
  settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  up: "ಮೇಲೆ",
  down: "ಕೆಳಗೆ",
  next6Hours: "ಮುಂದಿನ 6 ಗಂಟೆಗಳಲ್ಲಿ",
} as const;

export const aqiLabels = [
  "ಉತ್ತಮ",
  "ತೃಪ್ತಿಕರ",
  "ಮಧ್ಯಮ",
  "ಕಳಪೆ",
  "ಅತಿ ಕಳಪೆ",
  "ತೀವ್ರ",
] as const;
export const weatherLabels: Record<string, string> = {
  "0": "ನಿರ್ಮಲ ಆಕಾಶ",
  "1": "ಬಹುತೇಕ ನಿರ್ಮಲ",
  "2": "ಭಾಗಶಃ ಮೋಡ",
  "3": "ಮೋಡ ಕವಿದಿದೆ",
  "45": "ಮಂಜು",
  "48": "ಮಂಜು",
  "51": "ತುಂತುರು ಮಳೆ",
  "53": "ತುಂತುರು ಮಳೆ",
  "55": "ದಟ್ಟ ತುಂತುರು ಮಳೆ",
  "61": "ಹಗುರ ಮಳೆ",
  "63": "ಮಳೆ",
  "65": "ಭಾರಿ ಮಳೆ",
  "71": "ಹಗುರ ಹಿಮಪಾತ",
  "73": "ಹಿಮಪಾತ",
  "75": "ಭಾರಿ ಹಿಮಪಾತ",
  "80": "ಮಳೆಯ ಸಿಂಚನ",
  "81": "ಮಳೆ",
  "82": "ಭಾರಿ ಮಳೆ",
  "95": "ಗುಡುಗು ಸಹಿತ ಮಳೆ",
};
export const pushLabels: Record<string, string> = {
  breaking: "ಬ್ರೇಕಿಂಗ್ ಸುದ್ದಿ",
  live: "ನೇರಪ್ರಸಾರ",
  daily: "ದಿನದ ಮುಖ್ಯ ಸುದ್ದಿ",
  events: "ಕಾರ್ಯಕ್ರಮಗಳು",
  parva: "ಜೈನ ಪರ್ವಗಳು",
};

export const v4Choices: Record<string, string> = {
  draft: "ಕರಡು",
  published: "ಪ್ರಕಟಿತ",
  pending: "ಪರಿಶೀಲನೆಗೆ ಬಾಕಿ",
  approved: "ಅನುಮೋದಿತ",
  rejected: "ತಿರಸ್ಕೃತ",
  active: "ಸಕ್ರಿಯ",
  closed: "ಮುಕ್ತಾಯ",
  tag: "ಟ್ಯಾಗ್",
  topic: "ವಿಷಯ",
  page: "ಪುಟ",
  category: "ವರ್ಗ",
  external: "ಹೊರಗಿನ ಲಿಂಕ್",
  live: "ನೇರಪ್ರಸಾರ",
  parva: "ಪರ್ವ",
  tithi: "ತಿಥಿ",
  festival: "ಹಬ್ಬ",
  note: "ಟಿಪ್ಪಣಿ",
  job: "ಉದ್ಯೋಗ",
  scholarship: "ವಿದ್ಯಾರ್ಥಿವೇತನ",
  competition: "ಸ್ಪರ್ಧೆ",
  admission: "ಪ್ರವೇಶಾತಿ",
  shraddhanjali: "ಶ್ರದ್ಧಾಂಜಲಿ",
  abhinandane: "ಅಭಿನಂದನೆ",
  amantrana: "ಆಮಂತ್ರಣ",
  anniversary: "ವಾರ್ಷಿಕೋತ್ಸವ",
  sanmana: "ಸನ್ಮಾನ",
  student_achievement: "ವಿದ್ಯಾರ್ಥಿ ಸಾಧನೆ",
  gold22: "ಚಿನ್ನ 22K",
  gold24: "ಚಿನ್ನ 24K",
  silver: "ಬೆಳ್ಳಿ",
  petrol: "ಪೆಟ್ರೋಲ್",
  diesel: "ಡೀಸೆಲ್",
};
