export const hi = {
  home: "होम",
  videos: "वीडियो",
  search: "खोजें",
  events: "कार्यक्रम",
  account: "मेरा खाता",
  news: "समाचार",
  latest: "ताज़ा समाचार",
  allNews: "सभी समाचार",
  allVideos: "सभी वीडियो",
  allEvents: "सभी कार्यक्रम",
  readMore: "और पढ़ें",
  watch: "वीडियो देखें",
  live: "लाइव",
  breaking: "मुख्य समाचार",
  featured: "विशेष रिपोर्ट",
  upcoming: "आगामी कार्यक्रम",
  trending: "सर्वाधिक पढ़े गए",
  community: "हमारा समाज · हमारी आवाज़",
  tagline: "सत्य का प्रकाश। समाज की आवाज़।",
  edition: "कर्नाटक के जैन समाज का समाचार पोर्टल",
  sendNews: "अपनी खबर भेजें",
  sendTitle: "आपके गाँव-शहर की खबर के लिए यहाँ जगह है",
  sendDescription:
    "कार्यक्रम, उपलब्धि, समाजसेवा — अपने समाज की कहानी हमारे साथ साझा करें।",
  subscribe: "सूचनाएँ पाएँ",
  follow: "हमसे जुड़े रहें",
  about: "हमारे बारे में",
  contact: "संपर्क करें",
  advertise: "विज्ञापन",
  privacy: "गोपनीयता",
  terms: "नियम",
  disclaimer: "अस्वीकरण",
  sample: "नमूना संस्करण",
  sampleNote:
    "यहाँ दिए गए लेख और कार्यक्रम डिज़ाइन के नमूने हैं, वास्तविक समाचार नहीं।",
  eventDate: "कार्यक्रम तिथि",
  published: "प्रकाशन तिथि",
  place: "स्थान",
  readTime: "मिनट का पठन",
  searchPlaceholder: "समाचार, स्थान या कार्यक्रम खोजें…",
  keyword: "कीवर्ड",
  dateSearch: "तिथि से खोजें",
  from: "प्रारंभ तिथि",
  to: "अंतिम तिथि",
  category: "श्रेणी",
  allCategories: "सभी श्रेणियाँ",
  filter: "खोजें",
  clear: "साफ़ करें",
  noResults: "कोई समाचार नहीं मिला",
  tryAgain: "दूसरे शब्द या तिथि से फिर खोजें।",
  results: "परिणाम",
  searchHint:
    "कन्नड़ या अंग्रेज़ी में खोजें। उदा: श्रवणबेलगोला / shravanabelagola",
  save: "सहेजें",
  saved: "सहेजा गया",
  share: "साझा करें",
  copied: "लिंक कॉपी हो गया",
  related: "यह भी पढ़ें",
  keyPoints: "मुख्य बिंदु",
  backHome: "होम पर जाएँ",
  next: "आगे",
  previous: "पीछे",
  noVideo: "इस नमूना लेख में अभी वीडियो नहीं जोड़ा गया है।",
  videoLabel: "वीडियो रिपोर्ट",
  login: "लॉगिन",
  loginTitle: "हमारे समाज में आपका स्वागत है",
  loginDescription: "समाचार सहेजें और अपनी रुचि के कार्यक्रम याद रखें।",
  phone: "मोबाइल नंबर",
  phoneHint: "+91 सहित अपना मोबाइल नंबर",
  sendOtp: "OTP भेजें",
  otp: "6 अंकों का OTP",
  verify: "सत्यापित करें",
  google: "Google से जारी रखें",
  skip: "अभी नहीं",
  unavailable: "यह सेवा अभी तैयार हो रही है। कुछ समय बाद फिर प्रयास करें।",
  loginFailed: "लॉगिन नहीं हो सका। अपने विवरण जाँचें।",
  otpSent: "आपके मोबाइल पर OTP भेज दिया गया है।",
  logout: "लॉग आउट",
  savedPosts: "सहेजे गए समाचार",
  reminders: "कार्यक्रम अनुस्मारक",
  interests: "मेरी रुचियाँ",
  notifications: "सूचनाएँ",
  noSaved: "अभी कोई समाचार सहेजा नहीं गया है।",
  remind: "मुझे याद दिलाएँ",
  reminderSet: "अनुस्मारक जोड़ा गया",
  name: "आपका नाम",
  town: "गाँव / शहर",
  email: "ईमेल",
  message: "समाचार का विवरण",
  link: "वीडियो या चित्र का लिंक",
  submit: "समाचार भेजें",
  submitting: "भेजा जा रहा है…",
  submitted: "धन्यवाद। आपका समाचार हम तक पहुँच गया है।",
  validation: "सभी आवश्यक विवरण सही-सही भरें।",
  required: "आवश्यक",
  offline: "आप ऑफ़लाइन हैं",
  offlineDescription:
    "अभी इंटरनेट कनेक्शन नहीं है। पहले खोले गए समाचार पढ़ सकते हैं। कनेक्शन आने पर फिर प्रयास करें।",
  online: "इंटरनेट कनेक्शन वापस आ गया",
  retry: "फिर प्रयास करें",
  install: "ऐप के रूप में इंस्टॉल करें",
  installDescription: "समाचार और कार्यक्रम अब आपकी उँगलियों पर।",
  installButton: "इंस्टॉल",
  later: "बाद में",
  update: "नया संस्करण उपलब्ध है",
  refresh: "रिफ़्रेश",
  iosGuide: "Safari में शेयर बटन दबाएँ और ‘Add to Home Screen’ चुनें।",
  dark: "डार्क मोड",
  light: "लाइट मोड",
  menu: "मेनू खोलें",
  close: "बंद करें",
  skipContent: "मुख्य सामग्री पर जाएँ",
  calendar: "कार्यक्रम कैलेंडर",
  noEvents: "इस दिन कोई कार्यक्रम नहीं है।",
  organiser: "आयोजक",
  dateRange: "तिथि",
  eventDetails: "कार्यक्रम का विवरण",
  monthEvents: "इस माह के कार्यक्रम",
  footerText:
    "जैन समाज की खबरें, परंपरा, उपलब्धियाँ और संस्कृति आप तक पहुँचाने वाला विश्वसनीय मंच।",
  rights: "सर्वाधिकार सुरक्षित।",
  madeBy: "डिज़ाइन और विकास: MyDesignNexus",
  notFound: "यह पृष्ठ नहीं मिला",
  notFoundText: "लिंक बदल गया हो सकता है। होम पेज से फिर शुरू करें।",
  error: "पृष्ठ दिखाया नहीं जा सका",
  errorText: "कृपया कुछ समय बाद फिर प्रयास करें।",
  admin: "संपादकीय",
  dashboard: "डैशबोर्ड",
  posts: "लेख",
  categories: "श्रेणियाँ",
  submissions: "प्राप्त प्रविष्टियाँ",
  import: "आयात",
  users: "उपयोगकर्ता",
  settings: "सेटिंग्स",
  newPost: "नया लेख",
  title: "शीर्षक",
  draft: "मसौदा",
  publishedStatus: "प्रकाशित",
  status: "स्थिति",
  saveDraft: "मसौदा सहेजें",
  publish: "प्रकाशित करें",
  body: "लेख की सामग्री",
  summary: "सारांश",
  slug: "पृष्ठ का पता",
  videoUrl: "वीडियो लिंक",
  primary: "मुख्य श्रेणी",
  subscribeSuccess: "सूचनाओं के लिए पंजीकरण हो गया",
  subscribeError: "सूचनाएँ चालू नहीं हो सकीं। ब्राउज़र की अनुमतियाँ जाँचें।",
  demoArticle:
    "यह नमूना लेख है। यहाँ दिए गए कार्यक्रम के विवरण वास्तविक घोषणा नहीं हैं।",
  imageCredit: "चित्र सौजन्य",
  explore: "श्रेणी के अनुसार देखें",
  all: "सभी",
  shorts: "छोटे वीडियो",
  sort: "क्रमबद्ध करें",
  newest: "नए पहले",
  oldest: "पुराने पहले",
  year: "वर्ष",
  advertisement: "विज्ञापन",
  adSpace: "विज्ञापन के लिए आरक्षित स्थान",
  password: "ज्वालामाल पासवर्ड",
  confirmPassword: "पासवर्ड फिर दर्ज करें",
  showPassword: "पासवर्ड दिखाएँ",
  hidePassword: "पासवर्ड छिपाएँ",
  passwordHint: "कम से कम 8 अक्षरों का पासवर्ड रखें।",
  passwordMismatch: "दोनों पासवर्ड एक जैसे होने चाहिए।",
  appPasswordHint:
    "यहाँ अपना ज्वालामाल पासवर्ड ही डालें। Google खाते के लिए ऊपर दिया Google बटन उपयोग करें।",
  or: "अथवा",
  loginMethod: "लॉगिन का तरीका",
  emailLogin: "ईमेल से लॉगिन",
  phoneLogin: "मोबाइल OTP",
  createAccount: "नया खाता बनाएँ",
  forgotPassword: "पासवर्ड भूल गए?",
  sendReset: "रीसेट लिंक भेजें",
  backToLogin: "लॉगिन पर वापस",
  pleaseWait: "कृपया प्रतीक्षा करें…",
  confirmEmailSent:
    "खाते की पुष्टि के लिए अपना ईमेल देखें। खाता पहले से हो तो लॉगिन करें।",
  resetSent: "इस ईमेल पर खाता होने पर पासवर्ड रीसेट लिंक भेज दिया गया है।",
  authRequestFailed:
    "अनुरोध पूरा नहीं हो सका। विवरण जाँचें और कुछ समय बाद फिर प्रयास करें।",
  rateLimited:
    "ईमेल/OTP भेजने की सीमा पूरी हो गई है। कृपया कुछ मिनट रुककर फिर प्रयास करें।",
  googleLoginFailed: "Google लॉगिन शुरू नहीं हो सका। कृपया फिर प्रयास करें।",
  authLinkFailed:
    "लॉगिन लिंक की अवधि समाप्त हो गई है या वह मान्य नहीं है। कृपया फिर प्रयास करें।",
  changePhone: "मोबाइल नंबर बदलें",
  newPassword: "नया पासवर्ड बनाएँ",
  savePassword: "पासवर्ड सहेजें",
  passwordUpdated: "आपका पासवर्ड बदल गया है। अपने खाते पर आगे बढ़ें।",
  passwordUpdateFailed:
    "पासवर्ड नहीं बदला जा सका। फिर प्रयास करें या नया रीसेट लिंक प्राप्त करें।",
  categoryNews: "श्रेणी अनुसार समाचार",
  commentsHeading: "पाठकों की प्रतिक्रियाएँ",
  commentsNote:
    "सभी प्रतिक्रियाएँ समीक्षा के बाद दिखाई देती हैं। कृपया सम्मानपूर्वक लिखें।",
  commentsLoadFailed: "प्रतिक्रियाएँ लोड नहीं हो सकीं। फिर प्रयास करें।",
  yourComment: "आपकी प्रतिक्रिया",
  sendForReview: "समीक्षा के लिए भेजें",
  commentReceived: "समीक्षा के लिए प्राप्त हो गई।",
  commentFailed: "प्रतिक्रिया भेजी नहीं जा सकी।",
  tryLater: "कुछ समय बाद फिर प्रयास करें।",
  reportComment: "रिपोर्ट करें",
  reportSent: "रिपोर्ट समीक्षा के लिए भेज दी गई है।",
  reportFailed: "रिपोर्ट भेजी नहीं जा सकी।",
  reason: "कारण",
  send: "भेजें",
  connectionError: "कनेक्शन त्रुटि।",
  termsAndRefund: "नियम और रिफ़ंड नीति",
  agreeToTerms: "पढ़ लिए हैं और स्वीकार हैं।",
  oneTime: "एक बार",
  perMonth: "प्रति माह",
  perYear: "प्रति वर्ष",
  billingCyclesNote:
    "बिलिंग चक्रों तक स्वतः भुगतान। आगे के भुगतान आप अपने खाते से रद्द कर सकते हैं।",
  supportNow: "सहयोग करें",
  paymentConfirmed: "भुगतान की पुष्टि हो गई। आपके सहयोग के लिए धन्यवाद।",
  paymentPending:
    "भुगतान की जाँच चल रही है। पुष्ट भुगतान आपके खाते में दिखाई देगा।",
  paymentVerifyPending:
    "भुगतान की पुष्टि बाकी है। दोबारा भुगतान करने से पहले अपना खाता देखें।",
  paymentFailed: "भुगतान पूरा नहीं हुआ। अपने खाते में स्थिति जाँचें।",
  paymentStartFailed:
    "भुगतान शुरू नहीं हो सका। सदस्यता पहले से हो तो अपने खाते में जाँचें।",
  paymentServiceUnavailable: "भुगतान सेवा उपलब्ध नहीं है।",
  notificationTopics: "विषय",
  notificationsAllDevices: "सभी उपकरणों पर सूचनाएँ",
  dailyMax: "प्रतिदिन अधिकतम",
  quietStart: "शांत समय प्रारंभ (IST)",
  quietEnd: "शांत समय समाप्त (IST)",
  breakingOverride: "शांत समय में भी ब्रेकिंग समाचार की अनुमति",
  stopOnDevice: "इस उपकरण पर बंद करें",
  pushStoppedDevice: "इस उपकरण पर सूचनाएँ बंद कर दी गई हैं।",
  state: "राज्य",
  district: "ज़िला",
  cityOrTown: "नगर / गाँव",
  karnataka: "कर्नाटक",
  selectStateFirst: "पहले राज्य चुनें",
  selectDistrictFirst: "पहले ज़िला चुनें",
  noCities: "नगर अभी जोड़े नहीं गए हैं",
  membership: "सदस्यता",
  cancelSupportNote:
    "आगे के स्वतः भुगतान रद्द किए जा सकते हैं। जिस अवधि का भुगतान हो चुका है, उसकी सुविधाएँ जारी रहेंगी।",
  cancelRenewal: "नवीनीकरण रद्द करें",
  confirmStopPayments: "हाँ, आगे के भुगतान बंद करें",
  renewalCancelled: "आगे के भुगतान रद्द कर दिए गए हैं।",
  cancelFailed: "रद्द नहीं किया जा सका। कृपया हमसे संपर्क करें।",
  sponsorApproved: "अनुमोदित हो गया। अंतिम प्रकाशन का निर्णय संपादक लेते हैं।",
  sponsorApprovalIntro:
    "आप प्रायोजक की ओर से इस संस्करण की समीक्षा कर उसे अनुमोदित कर रहे हैं।",
  approveVersion: "इस संस्करण को अनुमोदित करें",
  sponsorLinkExpired:
    "संस्करण बदल गया है या लिंक की अवधि समाप्त हो गई है। नया लिंक प्राप्त करें।",
  openVideo: "वीडियो खोलें",
  resumeAt: "यहाँ से जारी रखें",
  startOver: "शुरू से",
  videoChapters: "वीडियो अध्याय",
  cancelReminder: "अनुस्मारक रद्द करें",
  notificationSettings: "सूचनाओं की सेटिंग",
  continueWatching: "देखना जारी रखें",
  featuredPhoto: "विशेष चित्र",
  onThisDay: "इतिहास में आज",
  loadingContent: "सामग्री लोड हो रही है…",
  closeAd: "विज्ञापन बंद करें",
  totalChoices: "कुल विकल्प",
  preferredSourceNote:
    "Google पर ज्वालामाल समाचार को पसंदीदा स्रोत के रूप में चुनें।",
  condolenceMessages: "शोक संदेश",
  messagesAfterReview: "संदेश समीक्षा के बाद प्रकाशित होते हैं।",
  readInKannada: "कन्नड़ में पढ़ें",
  readInEnglish: "अंग्रेज़ी में पढ़ें",
  readInHindi: "हिंदी में पढ़ें",
  machineTranslated: "कन्नड़ से मशीन अनुवाद, अभी समीक्षा नहीं हुई",
  sponsoredContent: "प्रायोजित सामग्री",
  contributorApplication: "नागरिक पत्रकार आवेदन",
  contributorIntro:
    "सत्यापित मोबाइल OTP से लॉगिन करें, फिर आवेदन भेजें। प्रशासक आपका आवेदन जाँचकर आपका रिपोर्टिंग क्षेत्र तय करते हैं। आपकी रचनाएँ संपादकीय समीक्षा के लिए मसौदे के रूप में सुरक्षित रहती हैं।",
  reportingArea: "रिपोर्टिंग क्षेत्र",
  yourExperience: "आपका अनुभव",
  applyNow: "आवेदन करें",
  applicationSent: "आवेदन समीक्षा के लिए भेज दिया गया है।",
  submitFailed: "भेजा नहीं जा सका।",
  contributorDetailsNeeded:
    "स्थान चुनें और अपने रिपोर्टिंग अनुभव का विवरण दें।",
  contributorPhoneNeeded:
    "फ़ोन OTP सत्यापन आवश्यक है। अपने विवरण जाँचकर फिर प्रयास करें।",
  earlyAccess: "सहयोगियों के लिए पूर्व पहुँच",
  noEarlyAccess: "आपके खाते के लिए कोई पूर्व-पहुँच समाचार उपलब्ध नहीं है।",
  supportBrand: "{brand} को सहयोग दें",
  supportIntro: "हमारे समाज की समाचार सेवा को आपका सहयोग।",
  payee: "भुगतान प्राप्तकर्ता",
  mySupportAndPayments: "मेरा सहयोग और भुगतान",
  supportPaymentsNotLive:
    "ऑनलाइन सहयोग भुगतान अभी शुरू नहीं हुए हैं। विवरण के लिए",
  contactUs: "हमसे संपर्क करें",
  supportTerms: "सहयोग के नियम",
  refundPolicy: "रिफ़ंड नीति",
  contactLabel: "संपर्क",
  supportTermsPending:
    "भुगतान सेवा शुरू होने से पहले नियम यहाँ प्रकाशित किए जाएँगे।",
  mySupport: "मेरा सहयोग",
  supporterActiveUntil: "सहयोगी · {date} तक सक्रिय",
  paymentHistory: "भुगतान इतिहास",
  date: "तिथि",
  amount: "राशि",
  paymentId: "भुगतान ID",
  paymentCaptured: "पुष्ट",
  refunded: "रिफ़ंड",
  noPayments: "कोई पुष्ट भुगतान नहीं।",
  citizenReporter: "नागरिक पत्रकार",
  earlyAccessShort: "पूर्व पहुँच",
  fullScreenStory: "पूर्ण स्क्रीन चित्रकथा",
  newsNearYou: "आपके क्षेत्र के समाचार",
  editorPicks: "संपादक की पसंद",
  pages: "पृष्ठ",
  siteLanguage: "साइट की भाषा",
};
export const v4hi = {
  correctionsIntro:
    "प्रकाशित रिपोर्टों के महत्वपूर्ण सुधार और स्पष्टीकरण यहाँ दर्ज किए जाते हैं। किसी रिपोर्ट में त्रुटि दिखे तो हमसे संपर्क करें।",
  noCorrections: "सुधार के दस्तावेज़ अभी प्रकाशित नहीं हुए हैं।",
  editorialPolicy: "संपादकीय नीति",
  factCheckPolicy: "तथ्य-जाँच नीति",
  theme: "दिखावट",
  systemTheme: "उपकरण के अनुसार",
  captionTooLong: "संदेश बहुत लंबा है। कम रिपोर्ट चुनें।",
  distributionReview:
    "चुनी गई प्रकाशित रिपोर्टों से मसौदा बनाएँ। पूरा संदेश जाँचकर भेजने के लिए अनुमोदित करें।",
  network: "नेटवर्क",
  createDraft: "मसौदा बनाएँ",
  queued: "भेजने की कतार में जोड़ दिया गया।",
  approveAndQueue: "जाँचकर भेजने के लिए अनुमोदित करें",
  channelId: "पेज / चैनल ID",
  accessToken: "सेवा का एक्सेस टोकन",
  activeSubscribers: "पुष्ट ग्राहक",
  jobs: "पृष्ठभूमि कार्य",
  status: "स्थिति",
  attempts: "प्रयास",
  audioPlayFailed:
    "ऑडियो शुरू नहीं हो सका। प्ले बटन दबाएँ या कुछ देर बाद प्रयास करें।",
  audioProgress: "ऑडियो प्रगति",
  audioSpeed: "सुनने की गति",
  liveReaders: "अभी पढ़ रहे पाठक",
  analyticsWindow:
    "पिछले 5 मिनट में दर्ज अनाम सत्र। नमूना सामग्री की गतिविधि नहीं गिनी जाती।",
  views: "पठन",
  engagedSeconds: "सक्रिय पठन के सेकंड",
  shares: "साझा",
  listens: "श्रवण",
  refresh: "ताज़ा करें",
  title: "शीर्षक",
  campaigns: "विज्ञापन अभियान",
  legacySlot: "पुराना विज्ञापन स्थान",
  image: "चित्र का लिंक",
  mobileImage: "मोबाइल चित्र का लिंक",
  alt: "चित्र विवरण",
  adSlots: "विज्ञापन स्थान",
  targetPages: "पृष्ठ प्रकार — प्रति पंक्ति एक",
  device: "उपकरण",
  weight: "प्रदर्शन भार",
  impressionCap: "कुल प्रदर्शन सीमा",
  clickCap: "कुल क्लिक सीमा",
  dailyCap: "दैनिक प्रदर्शन सीमा",
  sponsored: "प्रायोजित",
  adCspReady: "विज्ञापन सुरक्षा संरचना तैयार है।",
  adCspMissing:
    "वास्तविक Google विज्ञापन के लिए सर्वर पर ADS_STRICT_CSP=true सेट करना होगा।",
  format: "प्रारूप",
  creatives: "विज्ञापन चित्र",
  adReport: "विज्ञापन रिपोर्ट",
  impressions: "प्रदर्शन",
  clicks: "क्लिक",
  deskHint:
    "रिपोर्टों को चरणबद्ध रूप से संभालें। इस पैनल में चरण बदलने से रिपोर्ट स्वतः प्रकाशित नहीं होती।",
  unassigned: "किसी को नहीं सौंपा",
  assignee: "रिपोर्टर",
  priority: "प्राथमिकता",
  paragraph: "पैराग्राफ़ क्रमांक (पहला 0)",
  checkInbox: "अपने ईमेल में आया पुष्टि लिंक देखें।",
  newsletterHint:
    "अपनी पसंद का समाचार-पत्र ईमेल पर पाएँ। पुष्टि के बाद ही सदस्यता शुरू होती है। आप जब चाहें बंद कर सकते हैं।",
  frequency: "अंक की आवृत्ति",
  weekly: "साप्ताहिक",
  daily: "दैनिक",
  confirmNewsletter: "ईमेल सदस्यता की पुष्टि करें",
  subscriptionConfirmed: "सदस्यता की पुष्टि हो गई।",
  unsubscribed: "सदस्यता बंद कर दी गई।",
  linkExpired:
    "इस लिंक की अवधि समाप्त हो गई है या यह पहले ही उपयोग हो चुका है।",
  providerDisabled: "सेवा निष्क्रिय है या उपयोग की सीमा पूरी हो गई है।",
  aiSensitive: "इस श्रेणी में AI सुझाव निष्क्रिय कर दिए गए हैं।",
  aiSuggestion: "AI सुझाव",
  aiReview:
    "सुझावों की जाँच करें। चुने गए सुझाव का उपयोग करने के बाद रिपोर्ट को अलग से सहेजें।",
  generate: "सुझाव बनाएँ",
  accepted: "स्वीकृत",
  budgetNote:
    "मासिक सीमाएँ सेवा का खर्च नियंत्रित करती हैं। AI उपयोग में अधिकतम अनुमानित राशि पहले से आरक्षित कर ली जाती है।",
  credentialsReady: "सेवा की कुंजियाँ सेट हो गई हैं",
  credentialsMissing: "सेवा की कुंजियाँ अभी चाहिए",
  usage: "इस माह का उपयोग",
  monthlyLimit: "मासिक उपयोग सीमा",
  aiBlockedCategories: "AI से वर्जित श्रेणियाँ",
  role: "भूमिका",
  roles: "भूमिकाएँ और अनुमतियाँ",
  embargo: "प्रकाशन रोक का समय (IST)",
  quickSummary: "संक्षिप्त मुख्य बिंदु — प्रति पंक्ति एक",
  hideAds: "इस लेख में विज्ञापन छिपाएँ",
  meaningfulEdit: "पाठकों को बताने योग्य महत्वपूर्ण सुधार",
  locked: "इस रिपोर्ट को कोई अन्य संपादक संपादित कर रहे हैं।",
  restore: "मसौदे के रूप में बहाल करें",
  reviewNote: "समीक्षा टिप्पणी",
  publishChecklist:
    "प्रकाशन से पहले: तिथि, श्रेणी, सारांश, चित्र सौजन्य और 110 अक्षरों के भीतर शीर्षक जाँच लें।",
  samplePoll: "नमूना सर्वेक्षण — केवल आपके विकल्प की जाँच के लिए।",
  localOnly: "केवल इस उपकरण पर दर्ज किया गया है।",
  voteFailed:
    "मत दर्ज नहीं हो सका। मतदान समाप्त हो चुका हो सकता है या आपने पहले ही मत दिया हो सकता है।",
  totalVotes: "कुल मत",
  showScore: "परिणाम देखें",
  tryAgain: "फिर प्रयास करें",
  questions: "प्रश्न",
  reactions: "आपकी प्रतिक्रिया",
  namana: "नमन",
  useful: "उपयोगी",
  sad: "दुःख",
  thankYou: "धन्यवाद",
  waterLevel: "जलस्तर",
  recentReadings: "हाल के आँकड़े",
  noVerifiedData: "सत्यापित जानकारी अभी उपलब्ध नहीं है।",
  rateDisclaimer:
    "दरें प्रकाशित स्रोत और तिथि के अनुसार हैं। स्थानीय बाज़ार में दर अलग हो सकती है।",
  price: "दर",
  organization: "संस्था",
  feed: "आपके समाचार",
  syncFailed:
    "खाते के साथ जानकारी सिंक नहीं हो सकी। स्थानीय जानकारी सहेज ली गई है।",
  edit: "संपादन",
  select: "चुनें",
  answerNumberHint: "सही उत्तर का क्रमांक: पहला विकल्प 0, दूसरा विकल्प 1।",
  latitude: "अक्षांश",
  longitude: "देशांतर",
  credentials: "योग्यता और अनुभव",
  deity: "आराध्य देव",
  options: "विकल्प",
  fullLevel: "अधिकतम स्तर (m)",
  currentLevel: "आज का स्तर (m)",
  inflow: "आवक (cusecs)",
  outflow: "निकासी (cusecs)",
  value: "मान",
  unit: "इकाई",
  addRow: "पंक्ति जोड़ें",
  remove: "हटाएँ",
  caption: "चित्र का विवरण",
  note: "टिप्पणी",
  question: "प्रश्न",
  answer: "सही उत्तर",
  explanation: "स्पष्टीकरण",
  nearMe: "मेरे आसपास",
  savedPlace: "सहेजा गया स्थान",
  locationFailed: "स्थान का पता नहीं चल सका। सूची से अपना नगर चुनें।",
  rain: "वर्षा की संभावना",
  weatherAvailability:
    "सत्यापित मौसम जानकारी उपलब्ध होने पर यहाँ प्रकाशित होगी।",
  aqiNote:
    "यह मॉडल आधारित अनुमान है; किसी अधिकृत केंद्र का मापन नहीं। सूचकांक के लिए उपलब्ध 24 घंटे के PM2.5, PM10, NO₂ और SO₂ औसत उपयोग किए जाते हैं।",
  contentType: "सामग्री का प्रकार",
  trendingTopics: "अभी चर्चा में",
  topics: "विषय संग्रह",
  tags: "टैग",
  popularTags: "लोकप्रिय टैग",
  places: "स्थान",
  authors: "लेखक",
  series: "वीडियो श्रृंखला",
  episodes: "एपिसोड",
  keyFacts: "मुख्य जानकारी",
  timeline: "घटनाक्रम",
  pinned: "चुनी गई रिपोर्ट",
  archive: "समाचार संग्रह",
  allTopics: "सभी विषय",
  weather: "मौसम",
  jainCalendar: "जैन पंचांग",
  dailyTimes: "आज का समय",
  sunrise: "सूर्योदय",
  sunset: "सूर्यास्त",
  timeNote: "समय अनुमानित हैं; स्थानीय पंचांग देखें",
  observancePending:
    "धार्मिक आचरणों का समय समुदाय के सलाहकारों की समीक्षा के बाद जोड़ा जाएगा।",
  choosePlace: "स्थान चुनें",
  changePlace: "स्थान बदलें",
  updated: "अद्यतन",
  source: "स्रोत",
  stale: "पुरानी जानकारी",
  noWeather: "इस स्थान की मौसम जानकारी अभी उपलब्ध नहीं है।",
  forecast: "आगामी दिनों का पूर्वानुमान",
  hourly: "प्रति घंटा",
  temperature: "तापमान",
  humidity: "आर्द्रता",
  wind: "हवा",
  feelsLike: "अनुभव तापमान",
  airQuality: "वायु गुणवत्ता",
  estimated: "अनुमानित",
  dataUnavailable: "जानकारी अभी उपलब्ध नहीं",
  noCalendar: "इस माह के लिए सत्यापित पंचांग जानकारी अभी नहीं जोड़ी गई है।",
  basadis: "बसदियों का परिचय",
  notices: "समुदाय की सूचनाएँ",
  opportunities: "अवसर",
  district: "ज़िला",
  timings: "दर्शन समय",
  map: "नक्शा खोलें",
  relatedNews: "संबंधित समाचार",
  obituary: "श्रद्धांजलि",
  submitNotice: "सूचना भेजें",
  submitOpportunity: "अवसर की जानकारी भेजें",
  deadline: "अंतिम तिथि",
  organisation: "संस्था",
  apply: "विवरण देखें",
  job: "नौकरी",
  scholarship: "छात्रवृत्ति",
  competition: "प्रतियोगिता",
  admission: "प्रवेश",
  gallery: "चित्र संग्रह",
  stories: "चित्रकथाएँ",
  liveblogs: "लाइव रिपोर्टें",
  liveblog: "लाइव रिपोर्ट",
  newUpdates: "नए अपडेट",
  loadUpdates: "नए अपडेट दिखाएँ",
  ended: "लाइव रिपोर्ट समाप्त हो गई",
  polls: "आपकी राय",
  vote: "मत दें",
  pollClosed: "मतदान समाप्त हो गया",
  pollSaved: "आपका मत दर्ज हो गया",
  sampleVote: "यह नमूना मतदान है। परिणाम केवल इस उपकरण पर सहेजे जाते हैं।",
  quizzes: "प्रश्नोत्तरी",
  checkAnswer: "उत्तर जाँचें",
  score: "अंक",
  restart: "फिर से शुरू करें",
  reservoirs: "जलाशयों का जलस्तर",
  rates: "आज की दरें",
  storage: "संग्रह",
  rateGold22: "सोना 22K",
  rateGold24: "सोना 24K",
  rateSilver: "चांदी",
  ratePetrol: "पेट्रोल",
  rateDiesel: "डीज़ल",
  readingTools: "पढ़ने के विकल्प",
  textSize: "अक्षरों का आकार",
  lineSpace: "पंक्तियों का अंतर",
  contrast: "अधिक कंट्रास्ट",
  print: "प्रिंट करें",
  listen: "यह समाचार सुनें",
  pause: "रोकें",
  resume: "जारी रखें",
  stop: "बंद करें",
  readingTime: "पढ़ने का समय",
  minutes: "मिनट",
  follow: "फ़ॉलो करें",
  following: "फ़ॉलो कर रहे हैं",
  localFollow:
    "इस उपकरण पर सहेजा गया है। खाते में लॉगिन करने पर सिंक हो जाएगा।",
  myFeed: "आपके लिए",
  history: "पढ़े गए समाचार",
  clearHistory: "इतिहास साफ़ करें",
  newsletter: "समाचार-पत्र",
  subscribe: "सदस्य बनें",
  unsubscribe: "सदस्यता रद्द करें",
  newsletterNote: "ईमेल पर आए लिंक से अपनी सदस्यता की पुष्टि करें।",
  channels: "हमारे चैनल",
  editorial: "संपादकीय नीति",
  corrections: "सुधार",
  factcheck: "तथ्य-जाँच नीति",
  ownership: "स्वामित्व और वित्त",
  trustDraft:
    "यह नीति का मसौदा है। संस्था की समीक्षा और अनुमोदन के बाद अंतिम नीति प्रकाशित की जाएगी।",
  credit: "चित्र",
  nextEpisode: "अगला एपिसोड",
  previousStory: "पिछला समाचार",
  nextStory: "अगला समाचार",
  desk: "समाचार डेस्क",
  review: "समीक्षा",
  versions: "पिछले संस्करण",
  assistant: "संपादकीय सहायक",
  analytics: "पाठक आँकड़े",
  social: "सोशल मीडिया",
  providers: "सेवा सेटिंग्स",
  budgets: "उपयोग की सीमाएँ",
  moderation: "प्रकाशन की समीक्षा",
  pending: "समीक्षा के लिए लंबित",
  approved: "अनुमोदित",
  reject: "अस्वीकार करें",
  approve: "अनुमोदित करें",
  draft: "मसौदा",
  publish: "प्रकाशित करें",
  saveDraft: "मसौदा सहेजें",
  suggestions: "सुझाव",
  accept: "स्वीकार करें",
  enabled: "सक्रिय",
  disabled: "निष्क्रिय",
  start: "प्रारंभ",
  end: "समाप्ति",
  order: "क्रम",
  hide: "छिपाएँ",
  merge: "मिलाएँ",
  newItem: "नई प्रविष्टि",
  saved: "सहेजा गया",
  failed: "अनुरोध पूरा नहीं हो सका। फिर प्रयास करें।",
  serviceOff: "यह सेवा अभी सक्रिय नहीं है।",
  sample: "नमूना",
  readingHistoryEmpty: "आपने जो समाचार पढ़े हैं, वे यहाँ दिखाई देंगे।",
  noFollow: "आप जिन विषयों को फ़ॉलो करते हैं, उनके समाचार यहाँ दिखाई देंगे।",
  support: "ज्वालामाल को सहयोग",
  paymentsUnavailable: "सहयोग सेवा का विवरण शीघ्र ही प्रकाशित किया जाएगा।",
  openMenu: "सभी विभाग खोलें",
  closeMenu: "विभागों की सूची बंद करें",
  more: "अधिक",
  liveSample: "लाइव रिपोर्ट का नमूना",
  shareWhatsApp: "WhatsApp पर साझा करें",
  clear: "साफ़ करें",
  loading: "लोड हो रहा है…",
  shorts: "शॉर्ट्स",
  read: "पढ़ें",
  homeSections: "होम पेज के विभाग",
  adManager: "विज्ञापन प्रबंधन",
  import: "वीडियो आयात",
  report: "रिपोर्ट",
  exportCsv: "CSV डाउनलोड",
  settings: "सेटिंग्स",
  up: "ऊपर",
  down: "नीचे",
  next6Hours: "अगले 6 घंटों में",
};
export const monthsHi = [
  "जनवरी",
  "फ़रवरी",
  "मार्च",
  "अप्रैल",
  "मई",
  "जून",
  "जुलाई",
  "अगस्त",
  "सितंबर",
  "अक्तूबर",
  "नवंबर",
  "दिसंबर",
];
export const weekdaysHi = ["रवि", "सोम", "मंगल", "बुध", "गुरु", "शुक्र", "शनि"];
export const aqiLabelsHi = [
  "अच्छी",
  "संतोषजनक",
  "मध्यम",
  "खराब",
  "बहुत खराब",
  "गंभीर",
] as const;
export const weatherLabelsHi: Record<string, string> = {
  "0": "निर्मल आकाश",
  "1": "मुख्यतः निर्मल",
  "2": "आंशिक बादल",
  "3": "बादल छाए हुए",
  "45": "कोहरा",
  "48": "कोहरा",
  "51": "हल्की फुहार",
  "53": "फुहार",
  "55": "घनी फुहार",
  "61": "हल्की वर्षा",
  "63": "वर्षा",
  "65": "भारी वर्षा",
  "71": "हल्का हिमपात",
  "73": "हिमपात",
  "75": "भारी हिमपात",
  "80": "वर्षा की बूँदाबाँदी",
  "81": "वर्षा",
  "82": "भारी वर्षा",
  "95": "गरज के साथ वर्षा",
};
export const pushLabelsHi: Record<string, string> = {
  breaking: "ताज़ा ख़बर",
  live: "सीधा प्रसारण",
  daily: "दिन की मुख्य ख़बर",
  events: "कार्यक्रम",
  parva: "जैन पर्व",
};
