export const en = {
  home: "Home",
  videos: "Videos",
  search: "Search",
  events: "Events",
  account: "My account",
  news: "News",
  latest: "Latest news",
  allNews: "All News",
  allVideos: "All Videos",
  allEvents: "All Events",
  readMore: "Read More",
  watch: "Watch",
  live: "Live",
  breaking: "Headlines",
  featured: "Featured report",
  upcoming: "Upcoming events",
  trending: "Most read",
  community: "Our community · Our voice",
  tagline: "Light of truth. Voice of the community.",
  edition: "News for Karnataka’s Jain community",
  sendNews: "Send your news",
  sendTitle: "Your town’s stories belong here",
  sendDescription: "Share your community’s events, achievements and service.",
  subscribe: "Enable notifications",
  follow: "Stay connected",
  about: "About us",
  contact: "Contact",
  advertise: "Advertise",
  privacy: "Privacy",
  terms: "Terms",
  disclaimer: "Disclaimer",
  sample: "Sample edition",
  sampleNote: "These articles and events are design samples, not real news.",
  eventDate: "Event Date",
  published: "Published date",
  place: "Place",
  readTime: "min read",
  searchPlaceholder: "Search news, places or events…",
  keyword: "Keyword",
  dateSearch: "Search by date",
  from: "From date",
  to: "To date",
  category: "Category",
  allCategories: "All Categories",
  filter: "Search",
  clear: "Clear",
  noResults: "No stories found",
  tryAgain: "Try another word or date.",
  results: "Results",
  searchHint: "Search in Kannada or English, for example shravanabelagola.",
  save: "Save",
  saved: "Saved",
  share: "Share",
  copied: "Link copied",
  related: "Related stories",
  keyPoints: "Key Points",
  backHome: "Back to home",
  next: "Next",
  previous: "Previous",
  noVideo: "A video has not been added to this sample article.",
  videoLabel: "Video report",
  login: "Login",
  loginTitle: "Welcome to our community",
  loginDescription: "Save stories and keep track of events that interest you.",
  phone: "Phone",
  phoneHint: "Include your country code, for example +91.",
  sendOtp: "Send OTP",
  otp: "6-digit OTP",
  verify: "Verify",
  google: "Continue with Google",
  skip: "Not now",
  unavailable: "This service is not available yet.",
  loginFailed: "Sign-in failed. Check your details and try again.",
  otpSent: "Code sent. Check your phone.",
  logout: "Logout",
  savedPosts: "Saved Posts",
  reminders: "Reminders",
  interests: "Interests",
  notifications: "Notifications",
  noSaved: "No saved stories yet",
  remind: "Remind me",
  reminderSet: "Reminder saved",
  name: "Name",
  town: "Town",
  email: "Email",
  message: "Message",
  link: "Link",
  submit: "Submit",
  submitting: "Submitting…",
  submitted: "Received for review. Thank you.",
  validation: "Please check the entered details.",
  required: "Required",
  offline: "You are offline",
  offlineDescription:
    "Previously opened stories may still be available. Reconnect to load new stories.",
  online: "Back online",
  retry: "Retry",
  install: "Install Jwalamala",
  installDescription: "Keep community news and events close at hand.",
  installButton: "Install",
  later: "Later",
  update: "An update is available",
  refresh: "Refresh",
  iosGuide: "In Safari, tap Share and choose Add to Home Screen.",
  dark: "Dark",
  light: "Light",
  menu: "Open menu",
  close: "Close",
  skipContent: "Skip to content",
  calendar: "Calendar",
  noEvents: "No events found",
  organiser: "Organiser",
  dateRange: "Date Range",
  eventDetails: "Event Details",
  monthEvents: "This month’s events",
  footerText: "News, culture and community from Karnataka’s Jain society.",
  rights: "All rights reserved.",
  madeBy: "Created by",
  notFound: "Page not found",
  notFoundText: "The page you are looking for is unavailable.",
  error: "Something went wrong",
  errorText: "Please try again.",
  admin: "Admin",
  dashboard: "Dashboard",
  posts: "Posts",
  categories: "Categories",
  submissions: "Submissions",
  import: "Import",
  users: "Users",
  settings: "Settings",
  newPost: "New Post",
  title: "Title",
  draft: "Draft",
  publishedStatus: "Published",
  status: "Status",
  saveDraft: "Save Draft",
  publish: "Publish",
  body: "Body",
  summary: "Summary",
  slug: "Slug",
  videoUrl: "Video Url",
  primary: "Primary",
  subscribeSuccess: "Notifications enabled.",
  subscribeError:
    "Could not enable notifications. Check your browser permissions.",
  demoArticle:
    "This is sample content for design review, not a published news report.",
  imageCredit: "Image Credit",
  explore: "Explore",
  all: "All",
  shorts: "Shorts",
  sort: "Sort",
  newest: "Newest",
  oldest: "Oldest",
  year: "Year",
  advertisement: "Advertisement",
  adSpace: "Space reserved for advertising",
  password: "Password",
  confirmPassword: "Confirm Password",
  showPassword: "Show Password",
  hidePassword: "Hide Password",
  passwordHint: "Use at least 8 characters.",
  passwordMismatch: "The passwords do not match.",
  appPasswordHint:
    "Use your Jwalamala account password. Never enter your Google password here.",
  or: "or",
  loginMethod: "Login Method",
  emailLogin: "Email and password",
  phoneLogin: "Phone OTP",
  createAccount: "Create Account",
  forgotPassword: "Forgot password?",
  sendReset: "Send reset link",
  backToLogin: "Back To Login",
  pleaseWait: "Please wait…",
  confirmEmailSent: "Check your email to confirm your account.",
  resetSent: "If an account exists, a reset link has been sent.",
  authRequestFailed: "Could not complete the request. Try again.",
  rateLimited:
    "Too many email/OTP requests right now. Please wait a few minutes and try again.",
  googleLoginFailed: "Could not start Google sign-in.",
  authLinkFailed: "This sign-in link is invalid or expired.",
  changePhone: "Change Phone",
  newPassword: "New Password",
  savePassword: "Save Password",
  passwordUpdated: "Your password has been updated.",
  passwordUpdateFailed:
    "Could not update your password. Request a new reset link.",
  categoryNews: "News by category",
  commentsHeading: "Readers’ comments",
  commentsNote:
    "All comments appear after review. Please keep them respectful.",
  commentsLoadFailed: "Could not load comments. Please try again.",
  yourComment: "Your comment",
  sendForReview: "Send for review",
  commentReceived: "Received for review.",
  commentFailed: "Could not send your comment.",
  tryLater: "Please try again in a little while.",
  reportComment: "Report",
  reportSent: "Your report has been sent for review.",
  reportFailed: "Could not send the report.",
  reason: "Reason",
  send: "Send",
  connectionError: "Connection error.",
  termsAndRefund: "Terms and refund policy",
  agreeToTerms: "have been read and accepted.",
  oneTime: "one time",
  perMonth: "per month",
  perYear: "per year",
  billingCyclesNote:
    "billing cycles of automatic payments. You can cancel future payments from your account.",
  supportNow: "Support now",
  paymentConfirmed: "Payment confirmed. Thank you for your support.",
  paymentPending:
    "Your payment is being verified. Confirmed payments appear in your account.",
  paymentVerifyPending:
    "Payment verification is pending. Check your account before paying again.",
  paymentFailed:
    "The payment did not go through. Check the status in your account.",
  paymentStartFailed:
    "Could not start the payment. If you already have a membership, check your account.",
  paymentServiceUnavailable: "The payment service is unavailable.",
  notificationTopics: "Topics",
  notificationsAllDevices: "Notifications on all devices",
  dailyMax: "Daily maximum",
  quietStart: "Quiet hours start (IST)",
  quietEnd: "Quiet hours end (IST)",
  breakingOverride: "Allow breaking news during quiet hours",
  stopOnDevice: "Stop on this device",
  pushStoppedDevice: "Notifications have been stopped on this device.",
  state: "State",
  district: "District",
  cityOrTown: "City / town",
  selectStateFirst: "Select a state first",
  selectDistrictFirst: "Select a district first",
  noCities: "No cities added yet",
  membership: "Membership",
  cancelSupportNote:
    "You can cancel future automatic payments. The benefits of the period you have already paid for continue.",
  cancelRenewal: "Cancel renewal",
  confirmStopPayments: "Yes, stop future payments",
  renewalCancelled: "Future payments have been cancelled.",
  cancelFailed: "Could not cancel. Please contact us.",
  sponsorApproved: "Approved. Editors decide on the final publication.",
  sponsorApprovalIntro:
    "You are reviewing and approving this version on behalf of the sponsor.",
  approveVersion: "Approve this version",
  sponsorLinkExpired:
    "The version has changed or the link has expired. Request a new link.",
  openVideo: "Open video",
  resumeAt: "Resume at",
  startOver: "Start over",
  cancelReminder: "Cancel reminder",
  notificationSettings: "Notification settings",
  continueWatching: "Continue watching",
  featuredPhoto: "Featured photograph",
  onThisDay: "On this day",
  loadingContent: "Loading content…",
  closeAd: "Close advertisement",
  totalChoices: "Total choices",
  preferredSourceNote: "Choose Jwalamala as a preferred source on Google.",
  condolenceMessages: "Condolence messages",
  messagesAfterReview: "Messages are published after review.",
  readInKannada: "Read in Kannada",
  readInEnglish: "Read in English",
  sponsoredContent: "Sponsored content",
  contributorApplication: "Citizen reporter application",
  contributorIntro:
    "Sign in using a verified phone OTP, then apply. An administrator reviews your application and assigns your reporting area. Contributions are saved as drafts for editorial review.",
  reportingArea: "Reporting area",
  yourExperience: "Your experience",
  applyNow: "Apply",
  applicationSent: "Application sent for review.",
  submitFailed: "Unable to submit.",
  earlyAccess: "Early access for supporters",
  noEarlyAccess: "No early-access stories are available for your account.",
  supportBrand: "Support {brand}",
  supportIntro: "Your support for our community newsroom.",
  payee: "Payments received by",
  mySupportAndPayments: "My support and payments",
  supportPaymentsNotLive:
    "Online support payments have not started yet. For details",
  contactUs: "contact us",
  supportTerms: "Support terms",
  refundPolicy: "Refund policy",
  contactLabel: "Contact",
  supportTermsPending:
    "The terms will be published here before the payment service begins.",
  mySupport: "My support",
  supporterActiveUntil: "Supporter · active until {date}",
  paymentHistory: "Payment history",
  date: "Date",
  amount: "Amount",
  paymentId: "Payment ID",
  paymentCaptured: "Confirmed",
  refunded: "Refunded",
  noPayments: "No confirmed payments.",
  citizenReporter: "Citizen reporter",
  earlyAccessShort: "Early access",
  fullScreenStory: "Full-screen story",
  newsNearYou: "News near you",
};
export const v4en = {
  liveReaders: "Live Readers",
  analyticsWindow: "Analytics Window",
  views: "Views",
  engagedSeconds: "Engaged Seconds",
  shares: "Shares",
  listens: "Listens",
  refresh: "Refresh",
  title: "Title",
  campaigns: "Campaigns",
  legacySlot: "Legacy Slot",
  image: "Image",
  mobileImage: "Mobile Image",
  alt: "Alt",
  adSlots: "Ad Slots",
  targetPages: "Target Pages",
  device: "Device",
  weight: "Weight",
  impressionCap: "Impression Cap",
  clickCap: "Click Cap",
  dailyCap: "Daily Cap",
  sponsored: "Sponsored",
  adCspReady: "Ad Csp Ready",
  adCspMissing: "Ad Csp Missing",
  format: "Format",
  creatives: "Creatives",
  adReport: "Ad Report",
  impressions: "Impressions",
  clicks: "Clicks",
  deskHint: "Desk Hint",
  unassigned: "Unassigned",
  assignee: "Assignee",
  priority: "Priority",
  paragraph: "Paragraph",
  checkInbox: "Check Inbox",
  newsletterHint: "Newsletter Hint",
  frequency: "Frequency",
  weekly: "Weekly",
  daily: "Daily",
  confirmNewsletter: "Confirm Newsletter",
  subscriptionConfirmed: "Subscription Confirmed",
  unsubscribed: "Unsubscribed",
  linkExpired: "Link Expired",
  providerDisabled: "Provider Disabled",
  aiSensitive: "Ai Sensitive",
  aiSuggestion: "Ai Suggestion",
  aiReview: "Ai Review",
  generate: "Generate",
  accepted: "Accepted",
  budgetNote:
    "Providers are disabled until you enable them and set a monthly usage limit.",
  credentialsReady: "Credentials Ready",
  credentialsMissing: "Credentials Missing",
  usage: "Usage",
  monthlyLimit: "Monthly Limit",
  aiBlockedCategories: "Ai Blocked Categories",
  role: "Role",
  roles: "Roles",
  embargo: "Embargo",
  quickSummary: "Quick Summary",
  hideAds: "Hide Ads",
  meaningfulEdit: "Meaningful Edit",
  locked: "Locked",
  restore: "Restore",
  reviewNote: "Review Note",
  publishChecklist:
    "Before publishing: title up to 110 characters, summary, event date, image credit and primary category are required.",
  samplePoll: "Sample Poll",
  localOnly: "Local Only",
  voteFailed: "Vote Failed",
  totalVotes: "Total Votes",
  showScore: "Show Score",
  tryAgain: "Try Again",
  questions: "Questions",
  reactions: "Reactions",
  namana: "Namana",
  useful: "Useful",
  sad: "Sad",
  thankYou: "Thank You",
  waterLevel: "Water Level",
  recentReadings: "Recent Readings",
  noVerifiedData: "No Verified Data",
  rateDisclaimer: "Rate Disclaimer",
  price: "Price",
  organization: "Organization",
  feed: "Feed",
  syncFailed: "Sync Failed",
  edit: "Edit",
  select: "Select",
  answerNumberHint: "Answer Number Hint",
  latitude: "Latitude",
  longitude: "Longitude",
  credentials: "Credentials",
  deity: "Deity",
  options: "Options",
  fullLevel: "Full Level",
  currentLevel: "Current Level",
  inflow: "Inflow",
  outflow: "Outflow",
  value: "Value",
  unit: "Unit",
  addRow: "Add Row",
  remove: "Remove",
  caption: "Caption",
  note: "Note",
  question: "Question",
  answer: "Answer",
  explanation: "Explanation",
  nearMe: "Near Me",
  savedPlace: "Saved Place",
  locationFailed: "Location Failed",
  rain: "Rain",
  weatherAvailability: "Weather Availability",
  aqiNote: "Aqi Note",
  contentType: "Content Type",
  trendingTopics: "Trending now",
  topics: "Topics",
  tags: "Tags",
  popularTags: "Popular Tags",
  places: "Places",
  authors: "Authors",
  series: "Series",
  episodes: "Episodes",
  keyFacts: "Key Facts",
  timeline: "Timeline",
  pinned: "Pinned",
  archive: "Archive",
  allTopics: "All Topics",
  weather: "Weather",
  jainCalendar: "Jain calendar",
  dailyTimes: "Today’s timings",
  sunrise: "Sunrise",
  sunset: "Sunset",
  timeNote: "Times are approximate. Consult your local calendar.",
  observancePending:
    "Religious observance offsets await review by a community advisor. Only astronomical sunrise and sunset are shown.",
  choosePlace: "Choose Place",
  changePlace: "Change Place",
  updated: "Updated",
  source: "Source",
  stale: "Stale",
  noWeather: "Weather is not available for this place yet.",
  forecast: "Forecast",
  hourly: "Hourly",
  temperature: "Temperature",
  humidity: "Humidity",
  wind: "Wind",
  feelsLike: "Feels Like",
  airQuality: "Air Quality",
  estimated: "Estimated",
  dataUnavailable: "Data not yet available",
  noCalendar: "Verified calendar entries have not been added for this month.",
  basadis: "Basadi directory",
  notices: "Community notices",
  opportunities: "Opportunities",
  district: "District",
  timings: "Timings",
  map: "Map",
  relatedNews: "Related News",
  obituary: "In memoriam",
  submitNotice: "Submit Notice",
  submitOpportunity: "Submit Opportunity",
  deadline: "Deadline",
  organisation: "Organisation",
  apply: "View details",
  job: "Job",
  scholarship: "Scholarship",
  competition: "Competition",
  admission: "Admission",
  gallery: "Gallery",
  stories: "Web stories",
  liveblogs: "Live reports",
  liveblog: "Liveblog",
  newUpdates: "New Updates",
  loadUpdates: "Load Updates",
  ended: "Live report ended",
  polls: "Polls",
  vote: "Vote",
  pollClosed: "Voting has ended",
  pollSaved: "Your vote was recorded",
  sampleVote: "This is a sample poll. Results are stored only on this device.",
  quizzes: "Quizzes",
  checkAnswer: "Check Answer",
  score: "Score",
  restart: "Restart",
  reservoirs: "Reservoirs",
  rates: "Rates",
  storage: "Storage",
  readingTools: "Reading Tools",
  textSize: "Text Size",
  lineSpace: "Line spacing",
  contrast: "Contrast",
  print: "Print",
  listen: "Listen to this article",
  pause: "Pause",
  resume: "Resume",
  stop: "Stop",
  readingTime: "Reading Time",
  minutes: "Minutes",
  follow: "Follow",
  following: "Following",
  localFollow: "Saved on this device. Sign in to sync.",
  myFeed: "For you",
  history: "Reading history",
  clearHistory: "Clear History",
  newsletter: "Newsletter",
  subscribe: "Subscribe",
  unsubscribe: "Unsubscribe",
  newsletterNote:
    "Confirm your subscription using the link sent to your email.",
  channels: "Channels",
  editorial: "Editorial",
  corrections: "Corrections",
  factcheck: "Factcheck",
  ownership: "Ownership",
  trustDraft: "Trust Draft",
  credit: "Image credit",
  nextEpisode: "Next Episode",
  previousStory: "Previous Story",
  nextStory: "Next Story",
  desk: "Desk",
  review: "Review",
  versions: "Versions",
  assistant: "Assistant",
  analytics: "Analytics",
  social: "Social",
  providers: "Providers",
  budgets: "Budgets",
  moderation: "Moderation",
  pending: "Pending",
  approved: "Approved",
  reject: "Reject",
  approve: "Approve",
  draft: "Draft",
  publish: "Publish",
  saveDraft: "Save Draft",
  suggestions: "Suggestions",
  accept: "Accept",
  enabled: "Enabled",
  disabled: "Disabled",
  start: "Start",
  end: "End",
  order: "Order",
  hide: "Hide",
  merge: "Merge",
  newItem: "New Item",
  saved: "Saved",
  failed: "Could not complete the request. Please try again.",
  serviceOff: "This service is not enabled yet.",
  sample: "Sample",
  readingHistoryEmpty: "Stories you have read will appear here.",
  noFollow: "Follow topics to see their latest stories here.",
  support: "Support Jwalamala",
  paymentsUnavailable: "Support payments are not available yet.",
  openMenu: "Open all sections",
  closeMenu: "Close sections",
  more: "More",
  liveSample: "Live Sample",
  shareWhatsApp: "Share on WhatsApp",
  clear: "Clear",
  loading: "Loading",
  shorts: "Shorts",
  read: "Read",
  homeSections: "Home Sections",
  adManager: "Ad Manager",
  import: "Import",
  report: "Report",
  exportCsv: "Export Csv",
  settings: "Settings",
  up: "Up",
  down: "Down",
  theme: "Appearance",
  systemTheme: "System",
  sampleCalendar: "Sample calendar entry",
  noFollowedNews: "No stories match your follows yet.",
  correctionsIntro:
    "Significant corrections and clarifications to published reports are recorded here. Contact us if you spot an error in a report.",
  noCorrections: "No corrections have been published yet.",
  editorialPolicy: "Editorial policy",
  factCheckPolicy: "Fact-check policy",
  captionTooLong: "The message is too long. Select fewer reports.",
  distributionReview:
    "Create a draft from selected published reports. Review the full message and approve it for sending.",
  network: "Network",
  createDraft: "Create draft",
  queued: "Added to the sending queue.",
  approveAndQueue: "Approve and queue for sending",
  channelId: "Page / channel ID",
  accessToken: "Service access token",
  activeSubscribers: "Confirmed subscribers",
  jobs: "Background jobs",
  status: "Status",
  attempts: "Attempts",
  audioPlayFailed: "Audio could not be played.",
  audioProgress: "Audio progress",
  audioSpeed: "Playback speed",
  next6Hours: "next 6 hours",
};
export const monthsEn = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
export const weekdaysEn = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const aqiLabelsEn = [
  "Good",
  "Satisfactory",
  "Moderate",
  "Poor",
  "Very poor",
  "Severe",
] as const;
export const weatherLabelsEn: Record<string, string> = {
  "0": "Clear sky",
  "1": "Mainly clear",
  "2": "Partly cloudy",
  "3": "Overcast",
  "45": "Fog",
  "48": "Fog",
  "51": "Light drizzle",
  "53": "Drizzle",
  "55": "Heavy drizzle",
  "61": "Light rain",
  "63": "Rain",
  "65": "Heavy rain",
  "80": "Rain showers",
  "81": "Rain",
  "82": "Heavy rain",
  "95": "Thunderstorm",
};
