import {writeFile} from "node:fs/promises";
import {createHash} from "node:crypto";
import {v4Demo} from "../src/lib/v4/demo";
import {demoPosts,demoEvents} from "../src/lib/data/demo";
const ids=new Map<string,string>();
demoPosts.forEach((p,i)=>ids.set(p.id,"00000000-0000-4000-8000-"+String(1000+i).padStart(12,"0")));
demoEvents.forEach((e,i)=>ids.set(e.id,"00000000-0000-4000-8000-"+String(100+i).padStart(12,"0")));
function id(value:string){if(ids.has(value))return ids.get(value)!;const hash=createHash("sha256").update("jwalamala-v4:"+value).digest("hex");const uuid=hash.slice(0,8)+"-"+hash.slice(8,12)+"-4"+hash.slice(13,16)+"-8"+hash.slice(17,20)+"-"+hash.slice(20,32);ids.set(value,uuid);return uuid;}
function map(value:unknown,key=""):unknown{if(Array.isArray(value))return value.map(v=>map(v,key.endsWith("_ids")?"id":key));if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,map(v,k)]));if(typeof value==="string"&&(key==="id"||key.endsWith("_id")))return id(value);return value;}
function literal(value:unknown){if(value===null||value===undefined)return "null";if(typeof value==="boolean"||typeof value==="number")return String(value);return "'"+String(typeof value==="object"?JSON.stringify(value):value).replaceAll("'","''")+"'";}
const order=["tags","places","authors","series","jain_calendar_days","basadis","notices","opportunities","liveblogs","liveblog_updates","galleries","web_stories","polls","quizzes","topics","trending_items","post_tags","topic_pins","series_items","reservoir_readings"] as const;
const statements=["-- Development fixtures only; do not apply to a live newsroom.","-- Apply migrations and supabase/seed.sql first. Generated by scripts/generate-v4-seed.ts.","begin;"];
for(const table of order)for(const source of v4Demo[table]){const row=map(source) as Record<string,unknown>;const columns=Object.keys(row);statements.push("insert into public."+table+"("+columns.join(",")+") values("+columns.map(column=>column.endsWith("_ids")?"ARRAY["+(row[column] as string[]).map(literal).join(",")+"]::uuid[]":literal(row[column])).join(",")+") on conflict do nothing;");}
statements.push("commit;");await writeFile(new URL("../supabase/seed-v4.sql",import.meta.url),statements.join("\n")+"\n");
console.log("Generated v4 fixtures");
