create function public.is_staff() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and role in ('reporter','editor','admin')); $$;
create function public.has_role(r public.user_role) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and role=r); $$;
create function public.can_edit_post(pid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.posts p where p.id=pid and (public.has_role('admin') or public.has_role('editor') or (public.has_role('reporter') and p.author_id=(select auth.uid()) and p.status='draft'))); $$;
create function public.touch_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); return new; end; $$;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,full_name,phone) values(new.id,left(coalesce(new.raw_user_meta_data->>'full_name',''),100),new.phone); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create function public.protect_profile_role() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.role is distinct from old.role and (select auth.role())<>'service_role' and not public.has_role('admin') then raise exception 'Only administrators can change roles'; end if;return new;end; $$;
create trigger protect_role before update on public.profiles for each row execute function public.protect_profile_role();
create function public.audit_content() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.audit_log(actor_id,action,table_name,record_id,diff) values(auth.uid(),tg_op,tg_table_name,coalesce(to_jsonb(new)->>'id',to_jsonb(old)->>'id'),jsonb_build_object('old',to_jsonb(old),'new',to_jsonb(new)));return coalesce(new,old);end; $$;
create function public.enforce_primary_category() returns trigger language plpgsql set search_path='' as $$ declare pid uuid; begin if tg_table_name='posts' then pid=coalesce(new.id,old.id);else pid=coalesce(new.post_id,old.post_id);end if;if exists(select 1 from public.posts where id=pid and status in ('published','scheduled')) and (select count(*) from public.post_categories where post_id=pid and is_primary)<>1 then raise exception 'A publishable post needs exactly one primary category';end if;return null;end; $$;
create constraint trigger primary_post after insert or update on public.posts deferrable initially deferred for each row execute function public.enforce_primary_category();
create constraint trigger primary_relation after insert or update or delete on public.post_categories deferrable initially deferred for each row execute function public.enforce_primary_category();
create function public.publish_scheduled_posts() returns void language sql security definer set search_path='' as $$ update public.posts set status='published',published_at=now() where status='scheduled' and scheduled_for<=now() and event_date is not null; $$;
revoke all on function public.publish_scheduled_posts() from public,anon,authenticated;
grant execute on function public.publish_scheduled_posts() to service_role;
create function public.search_posts(q text default '',mode text default 'keyword',date_from date default null,date_to date default null,category_ids uuid[] default null,p_type public.post_type default null,p_limit int default 20,p_offset int default 0)
returns table(post jsonb,rank real,total_count bigint) language sql stable security invoker set search_path='' as $$
 with matched as (select p.*, (ts_rank(p.search_vector,websearch_to_tsquery('simple',q))+greatest(extensions.similarity(coalesce(p.title_en,''),q),extensions.similarity(coalesce(p.title_translit,''),q),extensions.similarity(p.title_kn,q)))::real as relevance
 from public.posts p where p.status='published' and p.published_at<=now()
 and (date_from is null or p.event_date>=date_from) and (date_to is null or p.event_date<=date_to)
 and (p_type is null or p.type=p_type)
 and (category_ids is null or exists(select 1 from public.post_categories pc where pc.post_id=p.id and pc.category_id=any(category_ids)))
 and (mode='event_date' or q='' or p.search_vector@@websearch_to_tsquery('simple',q) or p.title_kn ilike '%'||q||'%' or p.title_en ilike '%'||q||'%' or p.title_translit ilike '%'||q||'%'))
 select to_jsonb(matched)-'relevance',relevance,count(*) over() from matched order by relevance desc,published_at desc limit least(greatest(p_limit,1),100) offset greatest(p_offset,0); $$;
create function public.trending_posts(days int default 7,p_limit int default 10) returns setof public.posts language sql stable security invoker set search_path='' as $$ select p.* from public.posts p where p.status='published' and p.published_at<=now() order by p.view_count desc limit least(greatest(p_limit,1),100); $$;
create function public.consume_rate_limit(p_key text,p_max int,p_seconds int) returns boolean language plpgsql security definer set search_path='' as $$ declare n int;begin insert into public.rate_limits(key,hits,expires_at) values(p_key,1,now()+make_interval(secs=>p_seconds)) on conflict(key) do update set hits=case when public.rate_limits.expires_at<now() then 1 else public.rate_limits.hits+1 end,expires_at=case when public.rate_limits.expires_at<now() then now()+make_interval(secs=>p_seconds) else public.rate_limits.expires_at end returning hits into n;return n<=p_max;end; $$;
revoke all on function public.consume_rate_limit(text,int,int) from public,anon,authenticated;
grant execute on function public.consume_rate_limit(text,int,int) to service_role;
do $$ declare t text;begin foreach t in array array['profiles','categories','events','posts','post_categories','tags','post_tags','key_points','ads','submissions','bookmarks','event_reminders','push_subscriptions','redirects','site_settings','import_jobs','import_rows','post_views_daily','audit_log','rate_limits'] loop execute format('create trigger touch_updated_at before update on public.%I for each row execute function public.touch_updated_at()',t);end loop;foreach t in array array['posts','categories','events','ads','site_settings','redirects'] loop execute format('create trigger audit_change after insert or update or delete on public.%I for each row execute function public.audit_content()',t);end loop;end; $$;
