create table public.contributor_applications(user_id uuid primary key references public.profiles(id) on delete cascade,place_id uuid not null references public.places(id),note text not null check(char_length(note) between 10 and 2000),status text not null default 'pending' check(status in ('pending','approved','rejected')),approved_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.contributor_applications enable row level security;create policy own_read on public.contributor_applications for select to authenticated using(user_id=auth.uid() or public.has_permission('users.manage'));grant select on public.contributor_applications to authenticated;grant all on public.contributor_applications to service_role;
create function public.apply_contributor(place uuid,message text) returns void language plpgsql security definer set search_path='' as $$begin if auth.uid() is null or not exists(select 1 from auth.users where id=auth.uid() and phone_confirmed_at is not null) then raise exception 'Verify your phone with OTP first';end if;if char_length(message) not between 10 and 2000 then raise exception 'Invalid note';end if;insert into public.contributor_applications(user_id,place_id,note) values(auth.uid(),place,message) on conflict(user_id) do update set place_id=excluded.place_id,note=excluded.note,status='pending',approved_by=null,updated_at=now() where contributor_applications.status<>'approved';end;$$;
revoke all on function public.apply_contributor(uuid,text) from public,anon;grant execute on function public.apply_contributor(uuid,text) to authenticated;
create function public.review_contributor(target uuid,decision text) returns void language plpgsql security definer set search_path='' as $$declare application public.contributor_applications;begin if not public.has_permission('users.manage') or decision not in ('approved','rejected') then raise exception 'Not permitted';end if;select * into application from public.contributor_applications where user_id=target for update;if application.user_id is null then raise exception 'Application missing';end if;if decision='approved' and not exists(select 1 from auth.users where id=target and phone_confirmed_at is not null) then raise exception 'Phone verification required';end if;update public.contributor_applications set status=decision,approved_by=auth.uid(),updated_at=now() where user_id=target;if decision='approved' then update public.profiles set role='contributor',preferred_place_id=application.place_id where id=target;insert into public.authors(profile_id,slug,name_kn,role_kn,is_active) select id,'contributor-'||id,coalesce(nullif(full_name,''),'ನಾಗರಿಕ ವರದಿಗಾರ'),'ನಾಗರಿಕ ವರದಿಗಾರ',true from public.profiles where id=target and not exists(select 1 from public.authors where profile_id=target);end if;end;$$;
revoke all on function public.review_contributor(uuid,text) from public,anon;grant execute on function public.review_contributor(uuid,text) to authenticated;
create or replace function public.has_permission(requested text) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles p where p.id=auth.uid() and (p.role='admin' or (exists(select 1 from public.role_permissions rp where rp.role=p.role::text and rp.permission=requested and rp.allowed) and (p.role<>'contributor' or (requested in ('admin.access','content.create') and exists(select 1 from public.contributor_applications c join auth.users u on u.id=c.user_id where c.user_id=p.id and c.status='approved' and u.phone_confirmed_at is not null))))));$$;
create function public.contributor_post_defaults() returns trigger language plpgsql security definer set search_path='' as $$begin if exists(select 1 from public.profiles where id=auth.uid() and role='contributor') then if new.status<>'draft' or new.author_id<>auth.uid() then raise exception 'Contributor drafts require editorial review';end if;select place_id into new.place_id from public.contributor_applications where user_id=auth.uid() and status='approved';select id into new.public_author_id from public.authors where profile_id=auth.uid() and is_active order by created_at limit 1;end if;return new;end;$$;
create trigger contributor_defaults before insert or update on public.posts for each row execute function public.contributor_post_defaults();
