create table public.notice_billing(notice_id uuid primary key references public.notices(id) on delete cascade,amount_paise integer not null check(amount_paise between 100 and 100000000),payment_url text not null check(payment_url ~ '^https://(rzp[.]io|pages[.]razorpay[.]com)/'),status text not null default 'pending' check(status in ('pending','paid','waived')),payment_reference text not null default '',reviewed_by uuid references public.profiles(id),updated_at timestamptz not null default now(),check(status<>'paid' or char_length(payment_reference)>=4));alter table public.notice_billing enable row level security;
create policy billing_read on public.notice_billing for select to authenticated using(public.has_permission('ads.manage') or public.has_permission('community.manage'));
create policy billing_manage on public.notice_billing for all to authenticated using(public.has_permission('ads.manage')) with check(public.has_permission('ads.manage'));
grant select,insert,update on public.notice_billing to authenticated;grant all on public.notice_billing to service_role;
create function public.notice_payment_guard() returns trigger language plpgsql security definer set search_path='' as $$begin if new.status='approved' and exists(select 1 from public.notice_billing where notice_id=new.id and status='pending') then raise exception 'Notice payment must be reviewed before approval';end if;return new;end;$$;
create trigger notice_payment before insert or update on public.notices for each row execute function public.notice_payment_guard();
create trigger audit_billing after insert or update on public.notice_billing for each row execute function public.audit_content();

create function public.notice_billing_guard() returns trigger language plpgsql security definer set search_path='' as $$declare state text;begin select status into state from public.notices where id=new.notice_id for update;if state='approved' and new.status='pending' then raise exception 'Unapprove notice before requesting payment';end if;new.reviewed_by:=auth.uid();return new;end;$$;create trigger billing_guard before insert or update on public.notice_billing for each row execute function public.notice_billing_guard();
